from fastapi import APIRouter

router = APIRouter()

MODULOS_CPP = [
    {
        "id": 1, "bloque": "Fundamentos", "titulo": "Hola Mundo con cout",
        "descripcion": "Tu primer programa en C++", "xp": 50,
        "teoria": "C++ es un lenguaje compilado de alto rendimiento creado por Bjarne Stroustrup como extensión de C.\n\nDiferencias clave con Python/JS:\n• Se debe compilar antes de ejecutar\n• Tipado estático: declarás el tipo de cada variable\n• Más rápido en ejecución, más verboso\n• Manejo manual de memoria (aunque con smart pointers es más seguro)\n\nEstructura básica de un programa C++:\n• #include: incluye librerías\n• using namespace std: accede a cout, cin, etc. sin prefijo\n• int main(): función principal obligatoria\n• return 0: indica que el programa terminó correctamente\n• cout << : muestra en consola (equivalente a print/console.log)\n• endl o \\n: nueva línea",
        "ejemplo": '#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << "¡Hola, Mundo!" << endl;\n    cout << "Mi primer programa en C++" << endl;\n    cout << "El resultado de 5 + 3 es: " << 5 + 3 << endl;\n    cout << "Pi aproximado: " << 3.14159 << endl;\n    \n    // Múltiples valores en una línea\n    cout << "Año: " << 2026 << ", Lenguaje: C++" << endl;\n    \n    return 0;\n}',
        "ejercicio": "Escribí un programa que muestre:\n1. Tu nombre y tu lenguaje favorito\n2. El resultado de 3 operaciones matemáticas\n3. Una línea con múltiples valores concatenados con <<",
        "pista": "cout << \"texto\" << endl; — podés encadenar: cout << \"a\" << \" \" << \"b\" << endl;"
    },
    {
        "id": 2, "bloque": "Fundamentos", "titulo": "Variables tipadas",
        "descripcion": "Tipos de datos y variables en C++", "xp": 50,
        "teoria": "En C++ cada variable tiene un tipo fijo declarado en la compilación:\n\nTipos básicos:\n• int — entero (32 bits, -2B a 2B)\n• long long — entero grande (64 bits)\n• float — decimal de precisión simple (4 bytes)\n• double — decimal de doble precisión (8 bytes, más preciso)\n• char — carácter (1 byte)\n• bool — booleano (true/false)\n• string — texto (de #include <string>)\n\nDeclaración: tipo nombre = valor;\nAuto: C++11 permite que el compilador infiera el tipo.\n\nConstantes: const tipo nombre = valor;\nLiterales: 3.14f (float), 3.14 (double), 3L (long), 'A' (char)",
        "ejemplo": '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    int edad = 25;\n    double altura = 1.75;\n    float peso = 70.5f;\n    bool activo = true;\n    char inicial = \'A\';\n    string nombre = "Ana";\n    \n    cout << "Nombre: " << nombre << endl;\n    cout << "Edad: " << edad << endl;\n    cout << "Altura: " << altura << " m" << endl;\n    cout << "Activo: " << boolalpha << activo << endl;\n    cout << "Inicial: " << inicial << endl;\n    \n    // auto\n    auto pi = 3.14159; // double\n    auto lenguaje = string("C++"); // string\n    \n    // Constante\n    const double GRAVEDAD = 9.81;\n    cout << "Gravedad: " << GRAVEDAD << " m/s²" << endl;\n    \n    // Conversión (cast)\n    int entero = 7;\n    double decimal = (double)entero / 2;\n    cout << "7 / 2 = " << decimal << endl; // 3.5\n    \n    return 0;\n}',
        "ejercicio": "Declará variables de cada tipo básico (int, double, bool, char, string).\nCalculá el área de un círculo con radio=5.0 (usa const double PI = 3.14159265).\nConvertí un int a double para hacer división con decimales.\nMostrá todo con cout usando boolalpha para los booleanos.",
        "pista": "double area = PI * radio * radio; — Para división decimal: double resultado = (double)entero1 / entero2; — boolalpha hace que true/false se muestre como texto"
    },
    {
        "id": 3, "bloque": "Fundamentos", "titulo": "cin: entrada del usuario",
        "descripcion": "Leé datos del teclado con cin", "xp": 50,
        "teoria": "cin (character input) lee datos del teclado. Se usa con >> (extraction operator).\n\nSintaxis: cin >> variable;\n\nPara leer una línea completa (con espacios): getline(cin, string_variable);\n\nOjo: después de cin >> si querés usar getline, debés limpiar el buffer:\ncin.ignore(); o cin.ignore(numeric_limits<streamsize>::max(), '\\n');\n\nValidación: podés verificar si cin falló con if (!cin) { ... }\n\ncin >> automáticamente convierte el texto al tipo de la variable. Si el usuario escribe texto cuando esperás int, cin falla.\n\nPara múltiples variables: cin >> a >> b >> c;",
        "ejemplo": '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string nombre;\n    int edad;\n    double altura;\n    \n    cout << "¿Cuál es tu nombre? ";\n    getline(cin, nombre);\n    \n    cout << "¿Cuántos años tenés? ";\n    cin >> edad;\n    \n    cout << "¿Cuánto medís (metros)? ";\n    cin >> altura;\n    \n    cout << endl;\n    cout << "=== Tu perfil ===" << endl;\n    cout << "Nombre: " << nombre << endl;\n    cout << "Edad: " << edad << " años" << endl;\n    cout << "Altura: " << altura << " m" << endl;\n    cout << "En 10 años tendrás: " << edad + 10 << endl;\n    \n    // Leer múltiples valores\n    int a, b;\n    cout << "Ingresá dos números: ";\n    cin >> a >> b;\n    cout << "Suma: " << a + b << endl;\n    cout << "Producto: " << a * b << endl;\n    \n    return 0;\n}',
        "ejercicio": "Escribí un programa que:\n1. Pida nombre y año de nacimiento\n2. Calcule la edad (2026 - año)\n3. Pida el radio de un círculo\n4. Calcule y muestre área y perímetro\n5. Pida dos números y muestre suma, resta, producto, división",
        "pista": "Para evitar problemas con getline después de cin: cin.ignore(); getline(cin, nombre); — double area = 3.14159 * radio * radio;"
    },
    {
        "id": 4, "bloque": "Fundamentos", "titulo": "if / else y switch",
        "descripcion": "Condicionales en C++", "xp": 50,
        "teoria": "Las condicionales en C++ son muy similares a otros lenguajes pero con sintaxis de llaves {}:\n\nif (condicion) {\n    // código\n} else if (otra) {\n    // código\n} else {\n    // código\n}\n\nOperador ternario: condicion ? valor_si_true : valor_si_false;\n\nswitch: ideal para comparar una variable con valores constantes.\n• Cada case necesita break para no caer al siguiente\n• default: es como el else final\n\nOperadores de comparación: == != < > <= >=\nOperadores lógicos: && (and), || (or), ! (not)\n\nOjo: = es asignación, == es comparación. Error clásico: if (x = 5) siempre es true.",
        "ejemplo": '#include <iostream>\nusing namespace std;\n\nint main() {\n    double nota = 75.5;\n    \n    // if/else if/else\n    if (nota >= 90) {\n        cout << "Sobresaliente (A)" << endl;\n    } else if (nota >= 80) {\n        cout << "Notable (B)" << endl;\n    } else if (nota >= 70) {\n        cout << "Bien (C)" << endl;\n    } else if (nota >= 60) {\n        cout << "Suficiente (D)" << endl;\n    } else {\n        cout << "Insuficiente (F)" << endl;\n    }\n    \n    // Ternario\n    string resultado = (nota >= 60) ? "Aprobado" : "Reprobado";\n    cout << "Estado: " << resultado << endl;\n    \n    // switch\n    int mes = 3;\n    switch (mes) {\n        case 1: case 3: case 5: case 7:\n        case 8: case 10: case 12:\n            cout << "31 días" << endl; break;\n        case 4: case 6: case 9: case 11:\n            cout << "30 días" << endl; break;\n        case 2:\n            cout << "28 o 29 días" << endl; break;\n        default:\n            cout << "Mes inválido" << endl;\n    }\n    \n    return 0;\n}',
        "ejercicio": "Escribí un programa que:\n1. Pida un número entero y clasifique si es positivo, negativo o cero\n2. Si es positivo, diga si es par o impar\n3. Use switch para traducir un número (1-7) al nombre del día de la semana\n4. Use el operador ternario para mostrar 'mayor de edad' o 'menor de edad' según una edad dada",
        "pista": "if (n > 0) { if (n % 2 == 0) cout << \"par\"; else cout << \"impar\"; } — switch(dia) { case 1: cout << \"Lunes\"; break; ... }"
    },
    {
        "id": 5, "bloque": "Control de flujo", "titulo": "Bucles en C++",
        "descripcion": "for, while y do-while", "xp": 75,
        "teoria": "C++ tiene tres tipos de bucles:\n\nfor: ideal cuando conocés el número de iteraciones.\nfor (inicialización; condición; actualización) { ... }\n\nfor moderno (range-based for, C++11): for (tipo elemento : colección) { ... }\nEquivalente al for...of de JS o el for x in lista de Python.\n\nwhile: ejecuta mientras la condición sea true.\ndo-while: ejecuta al menos una vez, luego verifica.\n\nControl: break sale del bucle, continue salta a la siguiente iteración.\n\nBucles anidados: útiles para matrices y combinaciones. Cuidado con la complejidad O(n²).",
        "ejemplo": '#include <iostream>\nusing namespace std;\n\nint main() {\n    // for clásico\n    cout << "Conteo: ";\n    for (int i = 1; i <= 10; i++) {\n        cout << i << " ";\n    }\n    cout << endl;\n    \n    // for inverso\n    cout << "Inverso: ";\n    for (int i = 10; i >= 1; i--) {\n        cout << i << " ";\n    }\n    cout << endl;\n    \n    // Tabla de multiplicar\n    int num = 7;\n    cout << "Tabla del " << num << ":" << endl;\n    for (int i = 1; i <= 10; i++) {\n        cout << num << " x " << i << " = " << num * i << endl;\n    }\n    \n    // while: suma de dígitos\n    int n = 12345;\n    int suma = 0;\n    int temp = n;\n    while (temp > 0) {\n        suma += temp % 10;\n        temp /= 10;\n    }\n    cout << "Suma de dígitos de " << n << ": " << suma << endl;\n    \n    // do-while\n    int intento = 0;\n    do {\n        cout << "Intento " << ++intento << endl;\n    } while (intento < 3);\n    \n    return 0;\n}',
        "ejercicio": "1. Mostrá los números del 1 al 50 que son múltiplos de 3 o de 5 (con for)\n2. Calculá el factorial de 10 con while\n3. Imprimí un triángulo de asteriscos de altura N=5 (con bucles anidados)\n4. Encontrá el primer número > 100 que sea cuadrado perfecto",
        "pista": "Para triángulo: for(int i=1; i<=N; i++){ for(int j=0; j<i; j++) cout<<\"*\"; cout<<endl; } — para cuadrado perfecto: sqrt(n) == (int)sqrt(n) — #include <cmath>"
    },
    {
        "id": 6, "bloque": "Control de flujo", "titulo": "Funciones en C++",
        "descripcion": "Funciones tipadas y sobrecarga", "xp": 75,
        "teoria": "En C++, las funciones tienen tipos explícitos:\n• Tipo de retorno antes del nombre: int suma(int a, int b)\n• void si no devuelve nada\n• Declaración (prototipo) antes de main si se define después\n\nPaso de parámetros:\n• Por valor: la función recibe una copia (no modifica el original)\n• Por referencia (&): la función puede modificar el original\n• Por const referencia (const tipo&): eficiente sin permitir modificación\n\nSobrecarga (overloading): múltiples funciones con el mismo nombre pero diferentes parámetros.\n\nFunciones inline: sugerencia al compilador de expandir la función en cada llamada (eficiencia).\n\nFunciones template: genéricas para múltiples tipos (avanzado).",
        "ejemplo": '#include <iostream>\n#include <cmath>\nusing namespace std;\n\n// Prototipo (declaración)\ndouble areaCirculo(double radio);\nvoid intercambiar(int &a, int &b); // por referencia\n\n// Sobrecarga\ndouble sumar(double a, double b) { return a + b; }\nint sumar(int a, int b) { return a + b; }\nstring sumar(string a, string b) { return a + b; }\n\nint main() {\n    // Llamadas\n    cout << "Área círculo r=5: " << areaCirculo(5.0) << endl;\n    \n    int x = 10, y = 20;\n    cout << "Antes: x=" << x << ", y=" << y << endl;\n    intercambiar(x, y);\n    cout << "Después: x=" << x << ", y=" << y << endl;\n    \n    // Sobrecarga\n    cout << sumar(3, 4) << endl;         // 7 (int)\n    cout << sumar(3.5, 4.1) << endl;     // 7.6 (double)\n    cout << sumar("Hola ", "C++") << endl; // "Hola C++"\n    \n    return 0;\n}\n\ndouble areaCirculo(double radio) {\n    return M_PI * radio * radio;\n}\n\nvoid intercambiar(int &a, int &b) {\n    int temp = a;\n    a = b;\n    b = temp;\n}',
        "ejercicio": "Escribí las siguientes funciones:\n1. bool esPrimo(int n) — retorna true si n es primo\n2. int fibonacci(int n) — retorna el n-ésimo número de Fibonacci (recursivo)\n3. double potencia(double base, int exp) — calcula base^exp sin usar pow()\n4. Probá cada función y mostrá los resultados",
        "pista": "bool esPrimo: for(int i=2; i<=sqrt(n); i++) if(n%i==0) return false; return n>=2; — fibonacci: return n<=1 ? n : fibonacci(n-1)+fibonacci(n-2);"
    },
    {
        "id": 7, "bloque": "Estructuras de datos", "titulo": "Arrays y vectores STL",
        "descripcion": "Colecciones de datos en C++", "xp": 100,
        "teoria": "C++ tiene dos formas de manejar colecciones:\n\nArrays clásicos (C-style): tipo arr[tamaño] — tamaño fijo en compilación.\nLimitaciones: no saben su tamaño, no se pueden redimensionar.\n\nVector de STL: #include <vector> — como arrays dinámicos.\nVentajas: size(), push_back(), pop_back(), insert(), erase(), iteradores, se puede pasar fácilmente a funciones.\n\nMétodos principales de vector:\n• .push_back(x) — agrega al final\n• .pop_back() — elimina el último\n• .size() — cantidad de elementos\n• .at(i) — acceso con verificación de límites\n• .begin() / .end() — iteradores\n• .clear() — vacía el vector\n• .empty() — true si está vacío\n\nAlgoritmos de STL: #include <algorithm> — sort, find, min_element, max_element, etc.",
        "ejemplo": '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    // Array clásico\n    int arr[5] = {3, 1, 4, 1, 5};\n    for (int i = 0; i < 5; i++) {\n        cout << arr[i] << " ";\n    }\n    cout << endl;\n    \n    // Vector\n    vector<int> nums = {5, 2, 8, 1, 9, 3};\n    nums.push_back(7);\n    nums.push_back(4);\n    \n    cout << "Tamaño: " << nums.size() << endl;\n    \n    // Range-based for\n    for (int n : nums) {\n        cout << n << " ";\n    }\n    cout << endl;\n    \n    // Ordenar\n    sort(nums.begin(), nums.end());\n    cout << "Ordenado: ";\n    for (int n : nums) cout << n << " ";\n    cout << endl;\n    \n    // Min y max\n    cout << "Min: " << *min_element(nums.begin(), nums.end()) << endl;\n    cout << "Max: " << *max_element(nums.begin(), nums.end()) << endl;\n    \n    // Vector de strings\n    vector<string> paises = {"Argentina", "Chile", "México"};\n    paises.push_back("Colombia");\n    \n    for (const string& pais : paises) {\n        cout << pais << endl;\n    }\n    \n    return 0;\n}',
        "ejercicio": "1. Creá un vector de enteros del 1 al 20 con un bucle\n2. Separalos en dos vectores: pares e impares\n3. Calculá suma, promedio, mínimo y máximo del vector original\n4. Usá sort() para ordenar descendentemente (pista: rbegin/rend o comparador)",
        "pista": "sort(v.begin(), v.end(), greater<int>()); — para suma: int suma = 0; for(int n : nums) suma += n; — double prom = (double)suma / nums.size();"
    },
    {
        "id": 8, "bloque": "Estructuras de datos", "titulo": "Structs y clases",
        "descripcion": "OOP en C++: encapsulación y objetos", "xp": 100,
        "teoria": "C++ tiene dos formas de crear tipos compuestos:\n\nstruct: todos los miembros son public por defecto. Ideal para datos simples (POD - Plain Old Data).\n\nclass: todos los miembros son private por defecto. Usá para OOP completa con encapsulación.\n\nConceptos de OOP en C++:\n• Constructor: mismo nombre que la clase, sin tipo de retorno\n• Destructor: ~NombreClase(), se llama al liberar el objeto\n• this: puntero al objeto actual\n• Getters/setters: métodos para acceder a atributos privados\n• const methods: no modifican el objeto (void mostrar() const)\n• static members: compartidos por todos los objetos\n• Herencia: class Hija : public Padre\n• virtual: permite polimorfismo",
        "ejemplo": '#include <iostream>\n#include <string>\n#include <vector>\nusing namespace std;\n\nstruct Punto {\n    double x, y;\n    double distancia(const Punto& otro) const {\n        return sqrt(pow(x - otro.x, 2) + pow(y - otro.y, 2));\n    }\n};\n\nclass CuentaBancaria {\nprivate:\n    string titular;\n    double saldo;\n    int transacciones;\n\npublic:\n    CuentaBancaria(string titular, double saldoInicial = 0.0)\n        : titular(titular), saldo(saldoInicial), transacciones(0) {}\n    \n    bool depositar(double monto) {\n        if (monto <= 0) return false;\n        saldo += monto;\n        transacciones++;\n        return true;\n    }\n    \n    bool retirar(double monto) {\n        if (monto <= 0 || monto > saldo) return false;\n        saldo -= monto;\n        transacciones++;\n        return true;\n    }\n    \n    double getSaldo() const { return saldo; }\n    string getTitular() const { return titular; }\n    \n    void mostrar() const {\n        cout << "Titular: " << titular << endl;\n        cout << "Saldo: $" << saldo << endl;\n        cout << "Transacciones: " << transacciones << endl;\n    }\n};\n\nint main() {\n    Punto p1{0, 0}, p2{3, 4};\n    cout << "Distancia: " << p1.distancia(p2) << endl; // 5\n    \n    CuentaBancaria cuenta("Ana", 1000.0);\n    cuenta.depositar(500);\n    cuenta.retirar(200);\n    cuenta.mostrar();\n    \n    return 0;\n}',
        "ejercicio": "Implementá una clase Estudiante con:\n• Atributos privados: nombre, legajo, vector<double> notas\n• Constructor, getters para nombre y legajo\n• void agregarNota(double) con validación (0-10)\n• double promedio() const\n• bool aprobado() const (promedio >= 6)\n• void mostrar() const — imprime todo el perfil\n• Creá 3 estudiantes, agregá notas y mostrá quiénes aprobaron",
        "pista": "double promedio() const { if(notas.empty()) return 0; double s=0; for(double n:notas) s+=n; return s/notas.size(); }"
    },
    {
        "id": 9, "bloque": "STL avanzado", "titulo": "Stack y Queue con STL",
        "descripcion": "Estructuras de datos clásicas con la STL", "xp": 125,
        "teoria": "La STL (Standard Template Library) incluye adaptadores de contenedor:\n\nstack<T>: implementa LIFO (Last In, First Out)\n• push(x) — agrega al tope\n• pop() — elimina el tope (no devuelve el valor)\n• top() — devuelve el tope sin eliminar\n• empty() — true si vacía\n• size() — cantidad de elementos\n\nqueue<T>: implementa FIFO (First In, First Out)\n• push(x) — agrega al final\n• pop() — elimina el frente (no devuelve)\n• front() — elemento del frente\n• back() — elemento del fondo\n• empty() / size()\n\npriority_queue<T>: cola de prioridad (max-heap por defecto)\n\nmap<K,V>: diccionario ordenado por clave\nunordered_map<K,V>: diccionario hash (más rápido)",
        "ejemplo": '#include <iostream>\n#include <stack>\n#include <queue>\n#include <map>\n#include <string>\nusing namespace std;\n\nbool validarParentesis(const string& s) {\n    stack<char> pila;\n    for (char c : s) {\n        if (c == \'(\' || c == \'[\' || c == \'{\') {\n            pila.push(c);\n        } else if (c == \')\' || c == \']\' || c == \'}\') {\n            if (pila.empty()) return false;\n            char tope = pila.top();\n            pila.pop();\n            if ((c == \')\' && tope != \'(\') ||\n                (c == \']\' && tope != \'[\') ||\n                (c == \'}\' && tope != \'{\')) return false;\n        }\n    }\n    return pila.empty();\n}\n\nint main() {\n    // Stack\n    stack<int> pila;\n    for (int i = 1; i <= 5; i++) pila.push(i);\n    \n    cout << "Stack (LIFO): ";\n    while (!pila.empty()) {\n        cout << pila.top() << " ";\n        pila.pop();\n    }\n    cout << endl; // 5 4 3 2 1\n    \n    // Queue\n    queue<string> cola;\n    cola.push("Tarea 1"); cola.push("Tarea 2"); cola.push("Tarea 3");\n    \n    cout << "Queue (FIFO): ";\n    while (!cola.empty()) {\n        cout << cola.front() << " | ";\n        cola.pop();\n    }\n    cout << endl;\n    \n    // Validar paréntesis\n    cout << boolalpha;\n    cout << "({[]}): " << validarParentesis("({[]})") << endl; // true\n    cout << "([)]:  " << validarParentesis("([)]") << endl;    // false\n    \n    // map\n    map<string, int> frecuencia;\n    string palabras[] = {"hola", "mundo", "hola", "c++", "hola"};\n    for (const string& p : palabras) frecuencia[p]++;\n    for (const auto& [palabra, freq] : frecuencia)\n        cout << palabra << ": " << freq << endl;\n    \n    return 0;\n}',
        "ejercicio": "1. Usá stack para implementar una calculadora de notación postfija (RPN).\n   Ejemplo: \"3 4 + 2 *\" = (3+4)*2 = 14\n2. Usá queue para simular una cola de atención al cliente: agrega 5 clientes, atiende de a uno mostrando el orden\n3. Usá map para contar la frecuencia de caracteres en un string",
        "pista": "Para RPN: si es número haz push; si es operador, pop dos valores, opera y haz push del resultado. Al final top() es el resultado."
    },
    {
        "id": 10, "bloque": "Proyecto", "titulo": "Sistema completo",
        "descripcion": "Integrá todo en un sistema de gestión", "xp": 200,
        "teoria": "En este módulo final construirás un sistema completo que integra todos los conceptos:\n• Clases con herencia y polimorfismo\n• Vectores y mapas de STL\n• Funciones con referencias\n• Manejo de entrada/salida\n• Algoritmos de STL\n\nEl sistema es un Gestor de Biblioteca con:\n• Clase base Item con titulo, autor, año, disponible\n• Clase Libro (hereda de Item): ISBN, género, páginas\n• Clase Revista (hereda de Item): número, volumen\n• Clase Biblioteca: gestiona la colección\n• Operaciones: agregar, buscar, prestar, devolver, reportes\n\nConceptos avanzados usados:\n• Herencia pública\n• Métodos virtuales (polimorfismo)\n• Smart pointers (shared_ptr) para manejo seguro de memoria\n• Algoritmos de STL (sort, find_if)",
        "ejemplo": '#include <iostream>\n#include <vector>\n#include <string>\n#include <algorithm>\n#include <memory>\nusing namespace std;\n\nclass Item {\nprotected:\n    string titulo, autor;\n    int anio;\n    bool disponible;\npublic:\n    Item(string t, string a, int y)\n        : titulo(t), autor(a), anio(y), disponible(true) {}\n    virtual ~Item() = default;\n    \n    virtual void mostrar() const = 0; // método abstracto\n    string getTitulo() const { return titulo; }\n    bool isDisponible() const { return disponible; }\n    void prestar() { disponible = false; }\n    void devolver() { disponible = true; }\n};\n\nclass Libro : public Item {\n    string isbn, genero;\n    int paginas;\npublic:\n    Libro(string t, string a, int y, string isbn, string g, int p)\n        : Item(t, a, y), isbn(isbn), genero(g), paginas(p) {}\n    \n    void mostrar() const override {\n        cout << "[LIBRO] " << titulo << " - " << autor\n             << " (" << anio << ") | " << paginas << " págs\"\n             << " | " << (disponible ? "Disponible" : "Prestado") << endl;\n    }\n};\n\nclass Biblioteca {\n    vector<shared_ptr<Item>> catalogo;\npublic:\n    void agregar(shared_ptr<Item> item) {\n        catalogo.push_back(item);\n    }\n    \n    void mostrarTodo() const {\n        cout << "=== Catálogo (" << catalogo.size() << " items) ===" << endl;\n        for (const auto& item : catalogo) item->mostrar();\n    }\n    \n    bool prestar(const string& titulo) {\n        auto it = find_if(catalogo.begin(), catalogo.end(),\n            [&titulo](const shared_ptr<Item>& i) {\n                return i->getTitulo() == titulo && i->isDisponible();\n            });\n        if (it == catalogo.end()) return false;\n        (*it)->prestar();\n        return true;\n    }\n};\n\nint main() {\n    Biblioteca bib;\n    bib.agregar(make_shared<Libro>("El Principito","Saint-Exupéry",1943,"978-0","Ficción",96));\n    bib.agregar(make_shared<Libro>("Clean Code","Robert Martin",2008,"978-1","Técnico",431));\n    bib.mostrarTodo();\n    bib.prestar("El Principito");\n    cout << "\\nDespués de prestar:" << endl;\n    bib.mostrarTodo();\n    return 0;\n}',
        "ejercicio": "Extendé el sistema de Biblioteca:\n1. Agregá clase Revista que hereda de Item con número y volumen\n2. Agregá método buscarPorAutor(string) que devuelva vector<shared_ptr<Item>>\n3. Agregá método reporteEstadisticas() que muestre: total items, disponibles, prestados, % disponibilidad\n4. Agregá un menú interactivo con while + switch para usar el sistema",
        "pista": "Para buscarPorAutor: usa copy_if con lambda que compare autor. Para estadísticas: count_if(catalogo.begin(), catalogo.end(), [](auto& i){ return i->isDisponible(); });"
    }
]


@router.get("/modulos/cpp")
def get_modulos_cpp():
    return MODULOS_CPP
