from fastapi import APIRouter

router = APIRouter()

MODULOS_CPP = [
    {
        "id": 1, "bloque": "Fundamentos", "titulo": "Hola Mundo con cout",
        "descripcion": "Tu primer programa en C++", "xp": 50,
        "teoria": "C++ es un lenguaje compilado de alto rendimiento creado por Bjarne Stroustrup como extensión de C.\n\nDiferencias clave con Python/JS:\n• Se debe compilar antes de ejecutar\n• Tipado estático: declarás el tipo de cada variable\n• Más rápido en ejecución, más verboso\n• Manejo manual de memoria (aunque con smart pointers es más seguro)\n\nEstructura básica de un programa C++:\n• #include: incluye librerías\n• using namespace std: accede a cout, cin, etc. sin prefijo\n• int main(): función principal obligatoria\n• return 0: indica que el programa terminó correctamente\n• cout << : muestra en consola (equivalente a print/console.log)\n• endl o \\n: nueva línea",
        "ejemplo": '#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << "¡Hola, Mundo!" << endl;\n    cout << "Mi primer programa en C++" << endl;\n    cout << "El resultado de 5 + 3 es: " << 5 + 3 << endl;\n    cout << "Pi aproximado: " << 3.14159 << endl;\n    \n    // Múltiples valores en una línea\n    cout << "Año: " << 2026 << ", Lenguaje: C++" << endl;\n    \n    return 0;\n}',
        "ejercicio": "Escribí un programa que muestre:\n1. Tu nombre y tu lenguaje favorito\n2. El resultado de 3 operaciones matemáticas\n3. Una línea con múltiples valores concatenados con <<",
        "pista": "cout << \"texto\" << endl; — podés encadenar: cout << \"a\" << \" \" << \"b\" << endl;"
    },
    {
        "id": 2, "bloque": "Fundamentos", "titulo": "Variables tipadas",
        "descripcion": "Tipos de datos y variables en C++", "xp": 50,
        "teoria": "En C++ cada variable tiene un tipo fijo declarado en la compilación:\n\nTipos básicos:\n• int — entero (32 bits, -2B a 2B)\n• long long — entero grande (64 bits)\n• float — decimal de precisión simple (4 bytes)\n• double — decimal de doble precisión (8 bytes, más preciso)\n• char — carácter (1 byte)\n• bool — booleano (true/false)\n• string — texto (de #include <string>)\n\nDeclaración: tipo nombre = valor;\nAuto: C++11 permite que el compilador infiera el tipo.\n\nConstantes: const tipo nombre = valor;\nLiterales: 3.14f (float), 3.14 (double), 3L (long), 'A' (char)",
        "ejemplo": '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    int edad = 25;\n    double altura = 1.75;\n    float peso = 70.5f;\n    bool activo = true;\n    char inicial = \'A\';\n    string nombre = "Ana";\n    \n    cout << "Nombre: " << nombre << endl;\n    cout << "Edad: " << edad << endl;\n    cout << "Altura: " << altura << " m" << endl;\n    cout << "Activo: " << boolalpha << activo << endl;\n    cout << "Inicial: " << inicial << endl;\n    \n    // auto\n    auto pi = 3.14159; // double\n    auto lenguaje = string("C++"); // string\n    \n    // Constante\n    const double GRAVEDAD = 9.81;\n    cout << "Gravedad: " << GRAVEDAD << " m/s²" << endl;\n    \n    // Conversión (cast)\n    int entero = 7;\n    double decimal = (double)entero / 2;\n    cout << "7 / 2 = " << decimal << endl; // 3.5\n    \n    return 0;\n}',
        "ejercicio": "Declará variables de cada tipo básico (int, double, bool, char, string).\nCalculá el área de un círculo con radio=5.0 (usa const double PI = 3.14159265).\nConvertí un int a double para hacer división con decimales.\nMostrá todo con cout usando boolalpha para los booleanos.",
        "pista": "double area = PI * radio * radio; — Para división decimal: double resultado = (double)entero1 / entero2; — boolalpha hace que true/false se muestre como texto"
    },
    {
        "id": 3, "bloque": "Fundamentos", "titulo": "cin: entrada del usuario",
        "descripcion": "Leé datos del teclado con cin", "xp": 50,
        "teoria": "cin (character input) lee datos del teclado. Se usa con >> (extraction operator).\n\nSintaxis: cin >> variable;\n\nPara leer una línea completa (con espacios): getline(cin, string_variable);\n\nOjo: después de cin >> si querés usar getline, debés limpiar el buffer:\ncin.ignore(); o cin.ignore(numeric_limits<streamsize>::max(), '\\n');\n\nValidación: podés verificar si cin falló con if (!cin) { ... }\n\ncin >> automáticamente convierte el texto al tipo de la variable. Si el usuario escribe texto cuando esperás int, cin falla.\n\nPara múltiples variables: cin >> a >> b >> c;",
        "ejemplo": '#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string nombre;\n    int edad;\n    double altura;\n    \n    cout << "¿Cuál es tu nombre? ";\n    getline(cin, nombre);\n    \n    cout << "¿Cuántos años tenés? ";\n    cin >> edad;\n    \n    cout << "¿Cuánto medís (metros)? ";\n    cin >> altura;\n    \n    cout << endl;\n    cout << "=== Tu perfil ===" << endl;\n    cout << "Nombre: " << nombre << endl;\n    cout << "Edad: " << edad << " años" << endl;\n    cout << "Altura: " << altura << " m" << endl;\n    cout << "En 10 años tendrás: " << edad + 10 << endl;\n    \n    // Leer múltiples valores\n    int a, b;\n    cout << "Ingresá dos números: ";\n    cin >> a >> b;\n    cout << "Suma: " << a + b << endl;\n    cout << "Producto: " << a * b << endl;\n    \n    return 0;\n}',
        "ejercicio": "Escribí un programa que:\n1. Pida nombre y año de nacimiento\n2. Calcule la edad (2026 - año)\n3. Pida el radio de un círculo\n4. Calcule y muestre área y perímetro\n5. Pida dos números y muestre suma, resta, producto, división",
        "pista": "Para evitar problemas con getline después de cin: cin.ignore(); getline(cin, nombre); — double area = 3.14159 * radio * radio;"
    },
    {
        "id": 4, "bloque": "Fundamentos", "titulo": "if / else y switch",
        "descripcion": "Condicionales en C++", "xp": 50,
        "teoria": "Las condicionales en C++ son muy similares a otros lenguajes pero con sintaxis de llaves {}:\n\nif (condicion) {\n    // código\n} else if (otra) {\n    // código\n} else {\n    // código\n}\n\nOperador ternario: condicion ? valor_si_true : valor_si_false;\n\nswitch: ideal para comparar una variable con valores constantes.\n• Cada case necesita break para no caer al siguiente\n• default: es como el else final\n\nOperadores de comparación: == != < > <= >=\nOperadores lógicos: && (and), || (or), ! (not)\n\nOjo: = es asignación, == es comparación. Error clásico: if (x = 5) siempre es true.",
        "ejemplo": '#include <iostream>\nusing namespace std;\n\nint main() {\n    double nota = 75.5;\n    \n    // if/else if/else\n    if (nota >= 90) {\n        cout << "Sobresaliente (A)" << endl;\n    } else if (nota >= 80) {\n        cout << "Notable (B)" << endl;\n    } else if (nota >= 70) {\n        cout << "Bien (C)" << endl;\n    } else if (nota >= 60) {\n        cout << "Suficiente (D)" << endl;\n    } else {\n        cout << "Insuficiente (F)" << endl;\n    }\n    \n    // Ternario\n    string resultado = (nota >= 60) ? "Aprobado" : "Reprobado";\n    cout << "Estado: " << resultado << endl;\n    \n    // switch\n    int mes = 3;\n    switch (mes) {\n        case 1: case 3: case 5: case 7:\n        case 8: case 10: case 12:\n            cout << "31 días" << endl; break;\n        case 4: case 6: case 9: case 11:\n            cout << "30 días" << endl; break;\n        case 2:\n            cout << "28 o 29 días" << endl; break;\n        default:\n            cout << "Mes inválido" << endl;\n    }\n    \n    return 0;\n}',
        "ejercicio": "Escribí un programa que:\n1. Pida un número entero y clasifique si es positivo, negativo o cero\n2. Si es positivo, diga si es par o impar\n3. Use switch para traducir un número (1-7) al nombre del día de la semana\n4. Use el operador ternario para mostrar 'mayor de edad' o 'menor de edad' según una edad dada",
        "pista": "if (n > 0) { if (n % 2 == 0) cout << \"par\"; else cout << \"impar\"; } — switch(dia) { case 1: cout << \"Lunes\"; break; ... }"
    },
    {
        "id": 5, "bloque": "Control de flujo", "titulo": "Bucles en C++",
        "descripcion": "for, while y do-while", "xp": 75,
        "teoria": "C++ tiene tres tipos de bucles:\n\nfor: ideal cuando conocés el número de iteraciones.\nfor (inicialización; condición; actualización) { ... }\n\nfor moderno (range-based for, C++11): for (tipo elemento : colección) { ... }\nEquivalente al for...of de JS o el for x in lista de Python.\n\nwhile: ejecuta mientras la condición sea true.\ndo-while: ejecuta al menos una vez, luego verifica.\n\nControl: break sale del bucle, continue salta a la siguiente iteración.\n\nBucles anidados: útiles para matrices y combinaciones. Cuidado con la complejidad O(n²).",
        "ejemplo": '#include <iostream>\nusing namespace std;\n\nint main() {\n    // for clásico\n    cout << "Conteo: ";\n    for (int i = 1; i <= 10; i++) {\n        cout << i << " ";\n    }\n    cout << endl;\n    \n    // for inverso\n    cout << "Inverso: ";\n    for (int i = 10; i >= 1; i--) {\n        cout << i << " ";\n    }\n    cout << endl;\n    \n    // Tabla de multiplicar\n    int num = 7;\n    cout << "Tabla del " << num << ":" << endl;\n    for (int i = 1; i <= 10; i++) {\n        cout << num << " x " << i << " = " << num * i << endl;\n    }\n    \n    // while: suma de dígitos\n    int n = 12345;\n    int suma = 0;\n    int temp = n;\n    while (temp > 0) {\n        suma += temp % 10;\n        temp /= 10;\n    }\n    cout << "Suma de dígitos de " << n << ": " << suma << endl;\n    \n    // do-while\n    int intento = 0;\n    do {\n        cout << "Intento " << ++intento << endl;\n    } while (intento < 3);\n    \n    return 0;\n}',
        "ejercicio": "1. Mostrá los números del 1 al 50 que son múltiplos de 3 o de 5 (con for)\n2. Calculá el factorial de 10 con while\n3. Imprimí un triángulo de asteriscos de altura N=5 (con bucles anidados)\n4. Encontrá el primer número > 100 que sea cuadrado perfecto",
        "pista": "Para triángulo: for(int i=1; i<=N; i++){ for(int j=0; j<i; j++) cout<<\"*\"; cout<<endl; } — para cuadrado perfecto: sqrt(n) == (int)sqrt(n) — #include <cmath>"
    },
    {
        "id": 6, "bloque": "Control de flujo", "titulo": "Funciones en C++",
        "descripcion": "Funciones tipadas y sobrecarga", "xp": 75,
        "teoria": "En C++, las funciones tienen tipos explícitos:\n• Tipo de retorno antes del nombre: int suma(int a, int b)\n• void si no devuelve nada\n• Declaración (prototipo) antes de main si se define después\n\nPaso de parámetros:\n• Por valor: la función recibe una copia (no modifica el original)\n• Por referencia (&): la función puede modificar el original\n• Por const referencia (const tipo&): eficiente sin permitir modificación\n\nSobrecarga (overloading): múltiples funciones con el mismo nombre pero diferentes parámetros.\n\nFunciones inline: sugerencia al compilador de expandir la función en cada llamada (eficiencia).\n\nFunciones template: genéricas para múltiples tipos (avanzado).",
        "ejemplo": '#include <iostream>\n#include <cmath>\nusing namespace std;\n\n// Prototipo (declaración)\ndouble areaCirculo(double radio);\nvoid intercambiar(int &a, int &b); // por referencia\n\n// Sobrecarga\ndouble sumar(double a, double b) { return a + b; }\nint sumar(int a, int b) { return a + b; }\nstring sumar(string a, string b) { return a + b; }\n\nint main() {\n    // Llamadas\n    cout << "Área círculo r=5: " << areaCirculo(5.0) << endl;\n    \n    int x = 10, y = 20;\n    cout << "Antes: x=" << x << ", y=" << y << endl;\n    intercambiar(x, y);\n    cout << "Después: x=" << x << ", y=" << y << endl;\n    \n    // Sobrecarga\n    cout << sumar(3, 4) << endl;         // 7 (int)\n    cout << sumar(3.5, 4.1) << endl;     // 7.6 (double)\n    cout << sumar("Hola ", "C++") << endl; // "Hola C++"\n    \n    return 0;\n}\n\ndouble areaCirculo(double radio) {\n    const double PI = 3.14159265358979323846;\n    return PI * radio * radio;\n}\n\nvoid intercambiar(int &a, int &b) {\n    int temp = a;\n    a = b;\n    b = temp;\n}',
        "ejercicio": "Escribí las siguientes funciones:\n1. bool esPrimo(int n) — retorna true si n es primo\n2. int fibonacci(int n) — retorna el n-ésimo número de Fibonacci (recursivo)\n3. double potencia(double base, int exp) — calcula base^exp sin usar pow()\n4. Probá cada función y mostrá los resultados",
        "pista": "bool esPrimo: for(int i=2; i<=sqrt(n); i++) if(n%i==0) return false; return n>=2; — fibonacci: return n<=1 ? n : fibonacci(n-1)+fibonacci(n-2);"
    },
    {
        "id": 7, "bloque": "Estructuras de datos", "titulo": "Arrays y vectores STL",
        "descripcion": "Colecciones de datos en C++", "xp": 100,
        "teoria": "C++ tiene dos formas de manejar colecciones:\n\nArrays clásicos (C-style): tipo arr[tamaño] — tamaño fijo en compilación.\nLimitaciones: no saben su tamaño, no se pueden redimensionar.\n\nVector de STL: #include <vector> — como arrays dinámicos.\nVentajas: size(), push_back(), pop_back(), insert(), erase(), iteradores, se puede pasar fácilmente a funciones.\n\nMétodos principales de vector:\n• .push_back(x) — agrega al final\n• .pop_back() — elimina el último\n• .size() — cantidad de elementos\n• .at(i) — acceso con verificación de límites\n• .begin() / .end() — iteradores\n• .clear() — vacía el vector\n• .empty() — true si está vacío\n\nAlgoritmos de STL: #include <algorithm> — sort, find, min_element, max_element, etc.",
        "ejemplo": '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    // Array clásico\n    int arr[5] = {3, 1, 4, 1, 5};\n    for (int i = 0; i < 5; i++) {\n        cout << arr[i] << " ";\n    }\n    cout << endl;\n    \n    // Vector\n    vector<int> nums = {5, 2, 8, 1, 9, 3};\n    nums.push_back(7);\n    nums.push_back(4);\n    \n    cout << "Tamaño: " << nums.size() << endl;\n    \n    // Range-based for\n    for (int n : nums) {\n        cout << n << " ";\n    }\n    cout << endl;\n    \n    // Ordenar\n    sort(nums.begin(), nums.end());\n    cout << "Ordenado: ";\n    for (int n : nums) cout << n << " ";\n    cout << endl;\n    \n    // Min y max\n    cout << "Min: " << *min_element(nums.begin(), nums.end()) << endl;\n    cout << "Max: " << *max_element(nums.begin(), nums.end()) << endl;\n    \n    // Vector de strings\n    vector<string> paises = {"Argentina", "Chile", "México"};\n    paises.push_back("Colombia");\n    \n    for (const string& pais : paises) {\n        cout << pais << endl;\n    }\n    \n    return 0;\n}',
        "ejercicio": "1. Creá un vector de enteros del 1 al 20 con un bucle\n2. Separalos en dos vectores: pares e impares\n3. Calculá suma, promedio, mínimo y máximo del vector original\n4. Usá sort() para ordenar descendentemente (pista: rbegin/rend o comparador)",
        "pista": "sort(v.begin(), v.end(), greater<int>()); — para suma: int suma = 0; for(int n : nums) suma += n; — double prom = (double)suma / nums.size();"
    },
    {
        "id": 8, "bloque": "Estructuras de datos", "titulo": "Structs y clases",
        "descripcion": "OOP en C++: encapsulación y objetos", "xp": 100,
        "teoria": "C++ tiene dos formas de crear tipos compuestos:\n\nstruct: todos los miembros son public por defecto. Ideal para datos simples (POD - Plain Old Data).\n\nclass: todos los miembros son private por defecto. Usá para OOP completa con encapsulación.\n\nConceptos de OOP en C++:\n• Constructor: mismo nombre que la clase, sin tipo de retorno\n• Destructor: ~NombreClase(), se llama al liberar el objeto\n• this: puntero al objeto actual\n• Getters/setters: métodos para acceder a atributos privados\n• const methods: no modifican el objeto (void mostrar() const)\n• static members: compartidos por todos los objetos\n• Herencia: class Hija : public Padre\n• virtual: permite polimorfismo",
        "ejemplo": '#include <iostream>\n#include <string>\n#include <vector>\n#include <cmath>\nusing namespace std;\n\nstruct Punto {\n    double x, y;\n    double distancia(const Punto& otro) const {\n        return sqrt(pow(x - otro.x, 2) + pow(y - otro.y, 2));\n    }\n};\n\nclass CuentaBancaria {\nprivate:\n    string titular;\n    double saldo;\n    int transacciones;\n\npublic:\n    CuentaBancaria(string titular, double saldoInicial = 0.0)\n        : titular(titular), saldo(saldoInicial), transacciones(0) {}\n    \n    bool depositar(double monto) {\n        if (monto <= 0) return false;\n        saldo += monto;\n        transacciones++;\n        return true;\n    }\n    \n    bool retirar(double monto) {\n        if (monto <= 0 || monto > saldo) return false;\n        saldo -= monto;\n        transacciones++;\n        return true;\n    }\n    \n    double getSaldo() const { return saldo; }\n    string getTitular() const { return titular; }\n    \n    void mostrar() const {\n        cout << "Titular: " << titular << endl;\n        cout << "Saldo: $" << saldo << endl;\n        cout << "Transacciones: " << transacciones << endl;\n    }\n};\n\nint main() {\n    Punto p1{0, 0}, p2{3, 4};\n    cout << "Distancia: " << p1.distancia(p2) << endl; // 5\n    \n    CuentaBancaria cuenta("Ana", 1000.0);\n    cuenta.depositar(500);\n    cuenta.retirar(200);\n    cuenta.mostrar();\n    \n    return 0;\n}',
        "ejercicio": "Implementá una clase Estudiante con:\n• Atributos privados: nombre, legajo, vector<double> notas\n• Constructor, getters para nombre y legajo\n• void agregarNota(double) con validación (0-10)\n• double promedio() const\n• bool aprobado() const (promedio >= 6)\n• void mostrar() const — imprime todo el perfil\n• Creá 3 estudiantes, agregá notas y mostrá quiénes aprobaron",
        "pista": "double promedio() const { if(notas.empty()) return 0; double s=0; for(double n:notas) s+=n; return s/notas.size(); }"
    },
    {
        "id": 9, "bloque": "STL avanzado", "titulo": "Stack y Queue con STL",
        "descripcion": "Estructuras de datos clásicas con la STL", "xp": 125,
        "teoria": "La STL (Standard Template Library) incluye adaptadores de contenedor:\n\nstack<T>: implementa LIFO (Last In, First Out)\n• push(x) — agrega al tope\n• pop() — elimina el tope (no devuelve el valor)\n• top() — devuelve el tope sin eliminar\n• empty() — true si vacía\n• size() — cantidad de elementos\n\nqueue<T>: implementa FIFO (First In, First Out)\n• push(x) — agrega al final\n• pop() — elimina el frente (no devuelve)\n• front() — elemento del frente\n• back() — elemento del fondo\n• empty() / size()\n\npriority_queue<T>: cola de prioridad (max-heap por defecto)\n\nmap<K,V>: diccionario ordenado por clave\nunordered_map<K,V>: diccionario hash (más rápido)",
        "ejemplo": '#include <iostream>\n#include <stack>\n#include <queue>\n#include <map>\n#include <string>\nusing namespace std;\n\nbool validarParentesis(const string& s) {\n    stack<char> pila;\n    for (char c : s) {\n        if (c == \'(\' || c == \'[\' || c == \'{\') {\n            pila.push(c);\n        } else if (c == \')\' || c == \']\' || c == \'}\') {\n            if (pila.empty()) return false;\n            char tope = pila.top();\n            pila.pop();\n            if ((c == \')\' && tope != \'(\') ||\n                (c == \']\' && tope != \'[\') ||\n                (c == \'}\' && tope != \'{\')) return false;\n        }\n    }\n    return pila.empty();\n}\n\nint main() {\n    // Stack\n    stack<int> pila;\n    for (int i = 1; i <= 5; i++) pila.push(i);\n    \n    cout << "Stack (LIFO): ";\n    while (!pila.empty()) {\n        cout << pila.top() << " ";\n        pila.pop();\n    }\n    cout << endl; // 5 4 3 2 1\n    \n    // Queue\n    queue<string> cola;\n    cola.push("Tarea 1"); cola.push("Tarea 2"); cola.push("Tarea 3");\n    \n    cout << "Queue (FIFO): ";\n    while (!cola.empty()) {\n        cout << cola.front() << " | ";\n        cola.pop();\n    }\n    cout << endl;\n    \n    // Validar paréntesis\n    cout << boolalpha;\n    cout << "({[]}): " << validarParentesis("({[]})") << endl; // true\n    cout << "([)]:  " << validarParentesis("([)]") << endl;    // false\n    \n    // map\n    map<string, int> frecuencia;\n    string palabras[] = {"hola", "mundo", "hola", "c++", "hola"};\n    for (const string& p : palabras) frecuencia[p]++;\n    for (const auto& [palabra, freq] : frecuencia)\n        cout << palabra << ": " << freq << endl;\n    \n    return 0;\n}',
        "ejercicio": "1. Usá stack para implementar una calculadora de notación postfija (RPN).\n   Ejemplo: \"3 4 + 2 *\" = (3+4)*2 = 14\n2. Usá queue para simular una cola de atención al cliente: agrega 5 clientes, atiende de a uno mostrando el orden\n3. Usá map para contar la frecuencia de caracteres en un string",
        "pista": "Para RPN: si es número haz push; si es operador, pop dos valores, opera y haz push del resultado. Al final top() es el resultado."
    },
    {
        "id": 10, "bloque": "Algoritmos", "titulo": "Recursividad",
        "descripcion": "Funciones que se llaman a sí mismas", "xp": 125,
        "teoria": "Una función recursiva es una función que se llama a sí misma para resolver un problema dividiéndolo en subproblemas más chicos y del mismo tipo.\n\nToda función recursiva necesita:\n• Caso base: la condición donde la función deja de llamarse a sí misma y devuelve un valor directo. Sin caso base, la recursión nunca termina.\n• Caso recursivo: donde la función se llama a sí misma con un problema más chico, acercándose al caso base.\n\n¿Cómo funciona por dentro? Cada llamada se apila en el call stack (pila de llamadas). Cuando el caso base se alcanza, las llamadas empiezan a 'desapilarse' y devolver sus resultados hacia arriba.\n\nOjo: demasiadas llamadas recursivas sin llegar al caso base causan un stack overflow (desbordamiento de pila), un crash del programa.\n\nRecursión vs iteración: todo lo que se hace con recursión se puede hacer con un bucle, pero la recursión suele ser más clara para problemas que se dividen naturalmente en subproblemas (árboles, backtracking, divide y vencerás).",
        "ejemplo": '#include <iostream>\n#include <string>\nusing namespace std;\n\n// Caso base: n <= 1. Caso recursivo: n * factorial(n-1)\nlong long factorial(int n) {\n    if (n <= 1) return 1;         // caso base\n    return n * factorial(n - 1);  // caso recursivo\n}\n\n// Fibonacci recursivo clásico\nint fibonacci(int n) {\n    if (n <= 1) return n;\n    return fibonacci(n - 1) + fibonacci(n - 2);\n}\n\n// Suma de dígitos usando recursión\nint sumaDigitos(int n) {\n    if (n < 10) return n;\n    return n % 10 + sumaDigitos(n / 10);\n}\n\n// Potencia recursiva: base^exp\ndouble potencia(double base, int exp) {\n    if (exp == 0) return 1;\n    return base * potencia(base, exp - 1);\n}\n\nint main() {\n    cout << "5! = " << factorial(5) << endl;         // 120\n    cout << "10! = " << factorial(10) << endl;       // 3628800\n    \n    cout << "Fibonacci: ";\n    for (int i = 0; i < 10; i++) cout << fibonacci(i) << " ";\n    cout << endl;\n    \n    cout << "Suma de digitos de 4829: " << sumaDigitos(4829) << endl; // 23\n    cout << "2^10 = " << potencia(2, 10) << endl;     // 1024\n    \n    return 0;\n}',
        "ejercicio": "Escribí estas funciones recursivas (sin usar bucles):\n1. int mcd(int a, int b) — máximo común divisor con el algoritmo de Euclides (mcd(a,b) = mcd(b, a%b), caso base b==0)\n2. bool esPalindromo(string s, int inicio, int fin) — true si el string es palíndromo\n3. void invertirImprimir(vector<int> v, int i) — imprime el vector al revés usando recursión\n4. Probá cada una con al menos 2 casos",
        "pista": "mcd: if (b == 0) return a; return mcd(b, a % b); — palíndromo: si inicio>=fin return true; si s[inicio]!=s[fin] return false; sino llamá recursivamente con inicio+1, fin-1"
    },
    {
        "id": 11, "bloque": "Algoritmos", "titulo": "Complejidad algorítmica (Big O)",
        "descripcion": "Medí qué tan eficiente es tu código", "xp": 125,
        "teoria": "La notación Big O describe cómo crece el tiempo (o memoria) que usa un algoritmo a medida que crece el tamaño de la entrada (n). No mide segundos exactos, mide la tendencia de crecimiento.\n\nComplejidades comunes, de mejor a peor:\n• O(1) — constante: el tiempo no depende de n (acceder a arr[0])\n• O(log n) — logarítmica: divide el problema a la mitad en cada paso (búsqueda binaria)\n• O(n) — lineal: recorre todos los elementos una vez (un for simple)\n• O(n log n) — la de los buenes algoritmos de ordenamiento (mergesort, quicksort promedio)\n• O(n²) — cuadrática: bucles anidados sobre la misma colección (bubble sort)\n• O(2ⁿ) — exponencial: fibonacci recursivo sin memoización, backtracking sin poda\n\n¿Cómo calcularla? Contá cuántas veces se ejecuta la operación más costosa en función de n. Un for de 1 a n es O(n). Un for dentro de otro for, ambos hasta n, es O(n²). Ignorás constantes: O(2n) se simplifica a O(n).\n\nBig O importa porque un algoritmo O(n²) con n=1.000.000 puede tardar horas, mientras que uno O(n log n) tarda milisegundos.",
        "ejemplo": '#include <iostream>\n#include <vector>\n#include <chrono>\nusing namespace std;\nusing namespace std::chrono;\n\n// O(1) - constante\nint primerElemento(const vector<int>& v) {\n    return v[0];\n}\n\n// O(n) - lineal\nint sumaTotal(const vector<int>& v) {\n    int suma = 0;\n    for (int x : v) suma += x;  // 1 pasada\n    return suma;\n}\n\n// O(n^2) - cuadratica: bucles anidados\nbool tieneDuplicados(const vector<int>& v) {\n    for (size_t i = 0; i < v.size(); i++) {\n        for (size_t j = i + 1; j < v.size(); j++) {\n            if (v[i] == v[j]) return true;\n        }\n    }\n    return false;\n}\n\n// O(log n) - busqueda binaria (requiere vector ordenado)\nint busquedaBinaria(const vector<int>& v, int objetivo) {\n    int izq = 0, der = v.size() - 1;\n    while (izq <= der) {\n        int medio = izq + (der - izq) / 2;\n        if (v[medio] == objetivo) return medio;\n        if (v[medio] < objetivo) izq = medio + 1;\n        else der = medio - 1;\n    }\n    return -1;\n}\n\nint main() {\n    vector<int> datos;\n    for (int i = 0; i < 10000; i++) datos.push_back(i);\n    \n    auto inicio = high_resolution_clock::now();\n    long suma = sumaTotal(datos);\n    auto fin = high_resolution_clock::now();\n    cout << "Suma O(n): " << suma << " en " \n         << duration_cast<microseconds>(fin - inicio).count() << " us" << endl;\n    \n    cout << "Busqueda binaria de 7500: indice " << busquedaBinaria(datos, 7500) << endl;\n    cout << "Tiene duplicados: " << boolalpha << tieneDuplicados(datos) << endl;\n    \n    return 0;\n}',
        "ejercicio": "1. Clasificá la complejidad Big O de: recorrer un array una vez, dos bucles anidados sobre el mismo array, acceder a arr[5], fibonacci recursivo sin memoización\n2. Implementá busquedaLineal(vector<int>, objetivo) en O(n) y compará mentalmente con busquedaBinaria O(log n)\n3. Medí con chrono cuánto tarda sumaTotal() con un vector de 100, 100.000 y 10.000.000 elementos, y observá cómo crece el tiempo",
        "pista": "Para medir tiempo: auto t1 = high_resolution_clock::now(); ...codigo...; auto t2 = high_resolution_clock::now(); duration_cast<milliseconds>(t2-t1).count()"
    },
    {
        "id": 12, "bloque": "Algoritmos", "titulo": "Algoritmos de búsqueda y ordenamiento",
        "descripcion": "Bubble sort, quicksort conceptual y sort() de STL", "xp": 150,
        "teoria": "Ordenar y buscar son de los problemas más estudiados en programación.\n\nBubble sort (burbuja) — O(n²): compara pares adyacentes y los intercambia si están en el orden incorrecto, 'burbujeando' el mayor hacia el final en cada pasada. Simple pero ineficiente para datos grandes.\n\nQuicksort — O(n log n) promedio: elige un pivote, particiona el array en 'menores al pivote' y 'mayores al pivote', y ordena cada partición recursivamente (divide y vencerás). Es el algoritmo detrás de std::sort en la mayoría de implementaciones.\n\nEn la práctica: casi nunca implementás tu propio sort a mano en producción. C++ tiene std::sort() en <algorithm>, que es O(n log n) y está muy optimizado. Lo importante es entender CÓMO funcionan por dentro para saber cuándo un algoritmo es apropiado.\n\nBúsqueda lineal — O(n): recorre elemento por elemento. Funciona en cualquier colección.\nBúsqueda binaria — O(log n): requiere que la colección esté ordenada, pero es mucho más rápida.",
        "ejemplo": '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\n// Bubble sort manual - O(n^2)\nvoid bubbleSort(vector<int>& v) {\n    int n = v.size();\n    for (int i = 0; i < n - 1; i++) {\n        for (int j = 0; j < n - i - 1; j++) {\n            if (v[j] > v[j + 1]) {\n                swap(v[j], v[j + 1]);\n            }\n        }\n    }\n}\n\n// Quicksort manual - O(n log n) promedio\nvoid quickSort(vector<int>& v, int bajo, int alto) {\n    if (bajo >= alto) return;\n    int pivote = v[alto];\n    int i = bajo - 1;\n    for (int j = bajo; j < alto; j++) {\n        if (v[j] < pivote) {\n            i++;\n            swap(v[i], v[j]);\n        }\n    }\n    swap(v[i + 1], v[alto]);\n    int p = i + 1;\n    quickSort(v, bajo, p - 1);\n    quickSort(v, p + 1, alto);\n}\n\nint main() {\n    vector<int> a = {5, 2, 8, 1, 9, 3, 7};\n    bubbleSort(a);\n    cout << "Bubble sort: ";\n    for (int x : a) cout << x << " ";\n    cout << endl;\n    \n    vector<int> b = {5, 2, 8, 1, 9, 3, 7};\n    quickSort(b, 0, b.size() - 1);\n    cout << "Quicksort: ";\n    for (int x : b) cout << x << " ";\n    cout << endl;\n    \n    // En la práctica, usá std::sort\n    vector<int> c = {5, 2, 8, 1, 9, 3, 7};\n    sort(c.begin(), c.end());               // ascendente\n    sort(c.rbegin(), c.rend());             // descendente\n    cout << "std::sort descendente: ";\n    for (int x : c) cout << x << " ";\n    cout << endl;\n    \n    return 0;\n}',
        "ejercicio": "1. Implementá selectionSort(vector<int>&) — busca el mínimo en cada pasada y lo coloca al inicio\n2. Usá std::sort con un comparador lambda para ordenar un vector<pair<string,int>> (nombre, edad) por edad ascendente\n3. Implementá busquedaLineal(vector<int>, objetivo) que devuelva el índice o -1\n4. Compará: ordená un vector de 20 elementos con tu bubbleSort y con std::sort, verificá que dan el mismo resultado",
        "pista": "sort(v.begin(), v.end(), [](auto& a, auto& b){ return a.second < b.second; }); — selectionSort: en cada i buscá el índice del mínimo entre i y el final, luego swap con v[i]"
    },
    {
        "id": 13, "bloque": "Estructuras de datos avanzadas", "titulo": "Listas enlazadas",
        "descripcion": "Implementá una linked list desde cero", "xp": 150,
        "teoria": "Una lista enlazada (linked list) es una estructura de datos donde cada elemento (nodo) contiene un valor y un puntero al siguiente nodo. A diferencia de un array, no está en memoria contigua.\n\nVentajas sobre arrays:\n• Insertar/eliminar al principio es O(1), no requiere mover elementos\n• Tamaño dinámico sin necesidad de reservar de antemano\n\nDesventajas:\n• Acceso a un elemento por índice es O(n) (hay que recorrer desde el inicio)\n• Usa más memoria (cada nodo guarda un puntero extra)\n\nEstructura típica de un nodo:\nstruct Nodo {\n    int valor;\n    Nodo* siguiente;\n};\n\nOperaciones básicas: insertar al frente, insertar al final, eliminar un valor, buscar, recorrer e imprimir.\n\nEn C++ moderno se recomienda usar unique_ptr<Nodo> para que la memoria se libere automáticamente, pero para aprender la mecánica primero conviene verla con punteros crudos.",
        "ejemplo": '#include <iostream>\nusing namespace std;\n\nstruct Nodo {\n    int valor;\n    Nodo* siguiente;\n    Nodo(int v) : valor(v), siguiente(nullptr) {}\n};\n\nclass ListaEnlazada {\n    Nodo* cabeza;\npublic:\n    ListaEnlazada() : cabeza(nullptr) {}\n    \n    ~ListaEnlazada() {\n        Nodo* actual = cabeza;\n        while (actual) {\n            Nodo* siguiente = actual->siguiente;\n            delete actual;\n            actual = siguiente;\n        }\n    }\n    \n    void insertarFrente(int valor) {\n        Nodo* nuevo = new Nodo(valor);\n        nuevo->siguiente = cabeza;\n        cabeza = nuevo;\n    }\n    \n    void insertarFinal(int valor) {\n        Nodo* nuevo = new Nodo(valor);\n        if (!cabeza) { cabeza = nuevo; return; }\n        Nodo* actual = cabeza;\n        while (actual->siguiente) actual = actual->siguiente;\n        actual->siguiente = nuevo;\n    }\n    \n    bool eliminar(int valor) {\n        if (!cabeza) return false;\n        if (cabeza->valor == valor) {\n            Nodo* viejo = cabeza;\n            cabeza = cabeza->siguiente;\n            delete viejo;\n            return true;\n        }\n        Nodo* actual = cabeza;\n        while (actual->siguiente && actual->siguiente->valor != valor)\n            actual = actual->siguiente;\n        if (!actual->siguiente) return false;\n        Nodo* viejo = actual->siguiente;\n        actual->siguiente = viejo->siguiente;\n        delete viejo;\n        return true;\n    }\n    \n    void imprimir() const {\n        Nodo* actual = cabeza;\n        while (actual) {\n            cout << actual->valor << " -> ";\n            actual = actual->siguiente;\n        }\n        cout << "nullptr" << endl;\n    }\n};\n\nint main() {\n    ListaEnlazada lista;\n    lista.insertarFinal(1);\n    lista.insertarFinal(2);\n    lista.insertarFinal(3);\n    lista.insertarFrente(0);\n    lista.imprimir();  // 0 -> 1 -> 2 -> 3 -> nullptr\n    \n    lista.eliminar(2);\n    lista.imprimir();  // 0 -> 1 -> 3 -> nullptr\n    \n    return 0;\n}',
        "ejercicio": "Extendé ListaEnlazada con:\n1. int tamano() const — cuenta cuántos nodos hay\n2. bool contiene(int valor) const — busca un valor\n3. void invertir() — invierte el orden de la lista in-place (sin crear nodos nuevos)\n4. Probá todas las operaciones con una lista de al menos 5 elementos",
        "pista": "invertir(): mantené 3 punteros (anterior=nullptr, actual=cabeza, siguiente). En cada paso: siguiente=actual->siguiente; actual->siguiente=anterior; anterior=actual; actual=siguiente. Al final cabeza=anterior."
    },
    {
        "id": 14, "bloque": "Estructuras de datos avanzadas", "titulo": "Árboles binarios de búsqueda",
        "descripcion": "BST: inserción, búsqueda y recorridos", "xp": 150,
        "teoria": "Un árbol binario de búsqueda (BST - Binary Search Tree) es una estructura jerárquica donde cada nodo tiene como máximo dos hijos, y se cumple una regla de orden:\n• Todo valor en el subárbol izquierdo es MENOR que el nodo\n• Todo valor en el subárbol derecho es MAYOR que el nodo\n\nEsta propiedad hace que buscar, insertar y eliminar sean O(log n) en promedio (árbol balanceado), aunque en el peor caso (árbol degenerado, como una lista) sea O(n).\n\nRecorridos clásicos:\n• In-order (izquierda, nodo, derecha) — visita los valores en orden ascendente\n• Pre-order (nodo, izquierda, derecha) — útil para copiar/serializar el árbol\n• Post-order (izquierda, derecha, nodo) — útil para eliminar el árbol de forma segura\n\nUn BST es la base de estructuras más avanzadas como los mapas ordenados (map de STL usa un árbol balanceado internamente, típicamente red-black tree).",
        "ejemplo": '#include <iostream>\nusing namespace std;\n\nstruct NodoArbol {\n    int valor;\n    NodoArbol *izquierda, *derecha;\n    NodoArbol(int v) : valor(v), izquierda(nullptr), derecha(nullptr) {}\n};\n\nclass BST {\n    NodoArbol* raiz;\n    \n    NodoArbol* insertar(NodoArbol* nodo, int valor) {\n        if (!nodo) return new NodoArbol(valor);\n        if (valor < nodo->valor) nodo->izquierda = insertar(nodo->izquierda, valor);\n        else if (valor > nodo->valor) nodo->derecha = insertar(nodo->derecha, valor);\n        return nodo; // valores duplicados se ignoran\n    }\n    \n    bool buscar(NodoArbol* nodo, int valor) const {\n        if (!nodo) return false;\n        if (nodo->valor == valor) return true;\n        return valor < nodo->valor ? buscar(nodo->izquierda, valor) : buscar(nodo->derecha, valor);\n    }\n    \n    void inOrder(NodoArbol* nodo) const {\n        if (!nodo) return;\n        inOrder(nodo->izquierda);\n        cout << nodo->valor << " ";\n        inOrder(nodo->derecha);\n    }\n    \n    int altura(NodoArbol* nodo) const {\n        if (!nodo) return 0;\n        return 1 + max(altura(nodo->izquierda), altura(nodo->derecha));\n    }\n\npublic:\n    BST() : raiz(nullptr) {}\n    \n    void insertar(int valor) { raiz = insertar(raiz, valor); }\n    bool buscar(int valor) const { return buscar(raiz, valor); }\n    void imprimirInOrder() const { inOrder(raiz); cout << endl; }\n    int altura() const { return altura(raiz); }\n};\n\nint main() {\n    BST arbol;\n    for (int v : {50, 30, 70, 20, 40, 60, 80}) arbol.insertar(v);\n    \n    cout << "In-order (ordenado): ";\n    arbol.imprimirInOrder();  // 20 30 40 50 60 70 80\n    \n    cout << "Buscar 40: " << boolalpha << arbol.buscar(40) << endl;  // true\n    cout << "Buscar 99: " << boolalpha << arbol.buscar(99) << endl;  // false\n    cout << "Altura del arbol: " << arbol.altura() << endl;          // 3\n    \n    return 0;\n}',
        "ejercicio": "Extendé la clase BST con:\n1. int contarNodos() const — cuenta el total de nodos del árbol\n2. int minimo() const — devuelve el valor más chico (el nodo más a la izquierda)\n3. int maximo() const — devuelve el valor más grande (el nodo más a la derecha)\n4. void preOrder() const — imprime el recorrido pre-order\n5. Insertá al menos 8 valores y probá todos los métodos",
        "pista": "minimo(): desde la raíz, andá siempre a la izquierda hasta que izquierda sea nullptr, devolvé ese valor. contarNodos recursivo: if(!nodo) return 0; return 1 + contarNodos(izq) + contarNodos(der);"
    },
    {
        "id": 15, "bloque": "Estructuras de datos avanzadas", "titulo": "Grafos: BFS y DFS",
        "descripcion": "Recorré grafos en anchura y profundidad", "xp": 175,
        "teoria": "Un grafo es un conjunto de nodos (vértices) conectados por aristas (edges). Modela relaciones: ciudades y rutas, personas y amistades, páginas web y links.\n\nRepresentación común: lista de adyacencia — un map<int, vector<int>> donde cada nodo apunta a la lista de sus vecinos.\n\nBFS (Breadth-First Search, recorrido en anchura): explora el grafo nivel por nivel, usando una queue. Visita primero todos los vecinos directos, después los vecinos de los vecinos, etc. Ideal para encontrar el camino MÁS CORTO en grafos sin peso.\n\nDFS (Depth-First Search, recorrido en profundidad): explora tan lejos como puede por un camino antes de retroceder (backtrack), usando una stack (o recursión, que usa el call stack implícitamente). Ideal para detectar ciclos, componentes conexas, o explorar todas las rutas posibles.\n\nAmbos algoritmos son O(V + E) — V vértices, E aristas — y necesitan marcar nodos como 'visitados' para no procesarlos dos veces ni entrar en loops infinitos.",
        "ejemplo": '#include <iostream>\n#include <vector>\n#include <queue>\n#include <unordered_map>\n#include <unordered_set>\nusing namespace std;\n\nclass Grafo {\n    unordered_map<string, vector<string>> adyacencia;\npublic:\n    void agregarArista(const string& a, const string& b) {\n        adyacencia[a].push_back(b);\n        adyacencia[b].push_back(a); // grafo no dirigido\n    }\n    \n    void bfs(const string& inicio) const {\n        unordered_set<string> visitados;\n        queue<string> cola;\n        cola.push(inicio);\n        visitados.insert(inicio);\n        \n        cout << "BFS desde " << inicio << ": ";\n        while (!cola.empty()) {\n            string actual = cola.front();\n            cola.pop();\n            cout << actual << " ";\n            \n            auto it = adyacencia.find(actual);\n            if (it == adyacencia.end()) continue;\n            for (const string& vecino : it->second) {\n                if (!visitados.count(vecino)) {\n                    visitados.insert(vecino);\n                    cola.push(vecino);\n                }\n            }\n        }\n        cout << endl;\n    }\n    \n    void dfsUtil(const string& actual, unordered_set<string>& visitados) const {\n        visitados.insert(actual);\n        cout << actual << " ";\n        auto it = adyacencia.find(actual);\n        if (it == adyacencia.end()) return;\n        for (const string& vecino : it->second) {\n            if (!visitados.count(vecino)) dfsUtil(vecino, visitados);\n        }\n    }\n    \n    void dfs(const string& inicio) const {\n        unordered_set<string> visitados;\n        cout << "DFS desde " << inicio << ": ";\n        dfsUtil(inicio, visitados);\n        cout << endl;\n    }\n};\n\nint main() {\n    Grafo ciudades;\n    ciudades.agregarArista("Cordoba", "Rosario");\n    ciudades.agregarArista("Cordoba", "Mendoza");\n    ciudades.agregarArista("Rosario", "BuenosAires");\n    ciudades.agregarArista("Mendoza", "SanJuan");\n    ciudades.agregarArista("BuenosAires", "LaPlata");\n    \n    ciudades.bfs("Cordoba");\n    ciudades.dfs("Cordoba");\n    \n    return 0;\n}',
        "ejercicio": "Usando la clase Grafo:\n1. Modelá una red de 8 ciudades con al menos 9 conexiones\n2. Agregá un método bool hayCamino(origen, destino) que use BFS para determinar si existe un camino entre dos nodos\n3. Agregá un método vector<string> componenteConexa(nodo) que devuelva todos los nodos alcanzables desde uno dado (usando BFS o DFS)\n4. Probá con nodos conectados y con un nodo aislado (sin conexiones)",
        "pista": "hayCamino es igual que BFS pero cortás apenas encontrás el destino: if (actual == destino) return true; — al final del bucle, si nunca lo encontraste, return false;"
    },
    {
        "id": 16, "bloque": "Estructuras de datos avanzadas", "titulo": "Dijkstra: camino más corto",
        "descripcion": "Encontrá la ruta más barata en un grafo con pesos", "xp": 175,
        "teoria": "BFS encuentra el camino más corto en NÚMERO DE PASOS, pero no sirve si las conexiones tienen costos distintos (distancias, tiempos, precios). Para eso está el algoritmo de Dijkstra.\n\nDijkstra encuentra el camino de MENOR COSTO TOTAL desde un nodo origen hacia todos los demás, en un grafo con pesos no negativos.\n\nIdea del algoritmo:\n1. Asigná distancia 0 al origen e infinito a todos los demás nodos\n2. Usá una priority_queue (cola de prioridad) para siempre procesar el nodo con menor distancia acumulada conocida\n3. Para el nodo actual, revisá sus vecinos: si ir a través del nodo actual da una distancia MENOR que la que tenía registrada, actualizala (esto se llama 'relajar' la arista)\n4. Repetí hasta procesar todos los nodos\n\nComplejidad: O((V + E) log V) usando priority_queue — mucho mejor que revisar todas las combinaciones a fuerza bruta.\n\nAplicaciones reales: GPS y mapas (ruta más corta/rápida), enrutamiento de redes, juegos (pathfinding).",
        "ejemplo": '#include <iostream>\n#include <vector>\n#include <queue>\n#include <unordered_map>\n#include <climits>\nusing namespace std;\n\nclass GrafoConPeso {\n    unordered_map<string, vector<pair<string,int>>> adyacencia; // vecino, peso\npublic:\n    void agregarArista(const string& a, const string& b, int peso) {\n        adyacencia[a].push_back({b, peso});\n        adyacencia[b].push_back({a, peso});\n    }\n    \n    unordered_map<string,int> dijkstra(const string& origen) const {\n        unordered_map<string,int> distancias;\n        for (const auto& [nodo, _] : adyacencia) distancias[nodo] = INT_MAX;\n        distancias[origen] = 0;\n        \n        // min-heap de (distancia, nodo)\n        priority_queue<pair<int,string>, vector<pair<int,string>>, greater<>> pq;\n        pq.push({0, origen});\n        \n        while (!pq.empty()) {\n            auto [distActual, actual] = pq.top();\n            pq.pop();\n            \n            if (distActual > distancias[actual]) continue; // ya encontramos algo mejor\n            \n            for (const auto& [vecino, peso] : adyacencia.at(actual)) {\n                int nuevaDist = distActual + peso;\n                if (nuevaDist < distancias[vecino]) {\n                    distancias[vecino] = nuevaDist;\n                    pq.push({nuevaDist, vecino});\n                }\n            }\n        }\n        return distancias;\n    }\n};\n\nint main() {\n    GrafoConPeso rutas;\n    rutas.agregarArista("A", "B", 4);\n    rutas.agregarArista("A", "C", 1);\n    rutas.agregarArista("C", "B", 2);\n    rutas.agregarArista("B", "D", 5);\n    rutas.agregarArista("C", "D", 8);\n    \n    auto distancias = rutas.dijkstra("A");\n    for (const auto& [nodo, dist] : distancias) {\n        cout << "Distancia de A a " << nodo << ": " << dist << endl;\n    }\n    // A->C->B es 1+2=3, mejor que A->B directo que es 4\n    \n    return 0;\n}',
        "ejercicio": "1. Modelá un mapa de 6 ciudades con distancias reales entre ellas (kilómetros como peso)\n2. Corré dijkstra() desde una ciudad y mostrá la distancia mínima a todas las demás\n3. Agregá una función que reconstruya el CAMINO (no solo la distancia), guardando en un map<string,string> el 'nodo previo' de cada nodo cuando se relaja una arista\n4. Imprimí el camino completo desde el origen hasta un destino específico",
        "pista": "Para guardar el camino: unordered_map<string,string> previo; cada vez que actualizás distancias[vecino], hacé previo[vecino] = actual. Para reconstruir: partí del destino y seguí previo[] hacia atrás hasta llegar al origen."
    },
    {
        "id": 17, "bloque": "Memoria y bajo nivel", "titulo": "Punteros y referencias",
        "descripcion": "Entendé cómo C++ maneja direcciones de memoria", "xp": 150,
        "teoria": "Un puntero es una variable que guarda la DIRECCIÓN DE MEMORIA de otra variable, no su valor directamente. Es una de las características que distingue a C++ de Python/JS.\n\nOperadores clave:\n• & (address-of): obtiene la dirección de una variable\n• * (dereference): accede al valor apuntado por un puntero\n\nDeclaración: tipo* nombre = &variable;\n\nnullptr representa 'no apunta a nada'. Siempre inicializá los punteros (un puntero sin inicializar apunta a memoria basura, y usarlo es undefined behavior).\n\nReferencias (&): un alias de una variable existente, NO una dirección que se pueda reasignar. Una vez que una referencia se liga a una variable, no puede 'apuntar' a otra.\ntipo& ref = variable;\n\nDiferencias clave puntero vs referencia:\n• Un puntero puede ser nullptr, una referencia no\n• Un puntero se puede reasignar a otra dirección, una referencia no\n• Una referencia se usa como la variable original (sin *), un puntero necesita * para acceder al valor\n\n¿Cuándo usar cada uno? Referencias para pasar parámetros a funciones sin copiar (eficiente) y sin permitir null. Punteros cuando necesitás la posibilidad de 'no apuntar a nada' o reasignar a qué apuntan.",
        "ejemplo": '#include <iostream>\nusing namespace std;\n\nvoid porValor(int x) {\n    x = 100; // no afecta al original, es una copia\n}\n\nvoid porReferencia(int& x) {\n    x = 100; // SÍ afecta al original\n}\n\nvoid porPuntero(int* x) {\n    if (x != nullptr) *x = 100; // afecta al original, accediendo con *\n}\n\nint main() {\n    int a = 10;\n    \n    // Punteros básicos\n    int* p = &a;           // p guarda la dirección de a\n    cout << "Valor de a: " << a << endl;\n    cout << "Direccion de a: " << &a << endl;\n    cout << "p apunta a: " << p << endl;\n    cout << "Valor apuntado por p: " << *p << endl;\n    \n    *p = 50; // modifica a través del puntero\n    cout << "a despues de *p=50: " << a << endl; // 50\n    \n    // Referencias\n    int& ref = a; // ref es un alias de a\n    ref = 20;\n    cout << "a despues de ref=20: " << a << endl; // 20\n    \n    // Comparar los tres modos de paso de parámetros\n    int b = 5;\n    porValor(b);\n    cout << "Despues de porValor: " << b << endl;      // 5 (sin cambios)\n    \n    porReferencia(b);\n    cout << "Despues de porReferencia: " << b << endl;  // 100\n    \n    int c = 5;\n    porPuntero(&c);\n    cout << "Despues de porPuntero: " << c << endl;     // 100\n    \n    // Puntero nulo\n    int* nulo = nullptr;\n    if (nulo == nullptr) cout << "El puntero esta vacio, no lo desreferencio" << endl;\n    \n    return 0;\n}',
        "ejercicio": "1. Escribí una función intercambiar(int* a, int* b) que intercambie dos valores usando punteros (sin variable auxiliar visible desde afuera)\n2. Escribí duplicarEnSitio(int& x) que duplique el valor de x usando referencia\n3. Escribí una función que reciba un array (como puntero) y su tamaño, y devuelva un puntero al elemento máximo\n4. Probá cada función y verificá que los cambios se reflejan en las variables originales",
        "pista": "intercambiar: int temp = *a; *a = *b; *b = temp; — se llama así: intercambiar(&x, &y); — para el máximo: int* maxPtr = &arr[0]; for(...) if(arr[i] > *maxPtr) maxPtr = &arr[i];"
    },
    {
        "id": 18, "bloque": "Memoria y bajo nivel", "titulo": "Memoria dinámica y smart pointers",
        "descripcion": "new, delete y punteros inteligentes modernos", "xp": 175,
        "teoria": "La memoria de un programa se divide en:\n• Stack (pila): variables locales, se liberan automáticamente al salir de su scope. Rápida pero limitada en tamaño.\n• Heap (montículo): memoria que reservás manualmente con new, y que persiste hasta que la liberás con delete. Más flexible, pero VOS sos responsable de liberarla.\n\nMemoria dinámica clásica (C-style):\nint* p = new int(5);   // reserva un int en el heap\ndelete p;               // libera esa memoria\n\nint* arr = new int[10]; // reserva un array\ndelete[] arr;            // libera un array (¡con corchetes!)\n\nProblema: si te olvidás del delete, tenés un MEMORY LEAK (fuga de memoria) — memoria reservada que nunca se libera. Si hacés delete dos veces o usás un puntero después de liberarlo (dangling pointer), es undefined behavior.\n\nSolución moderna: smart pointers (<memory>), que liberan la memoria automáticamente cuando ya no se necesitan (RAII - Resource Acquisition Is Initialization):\n• unique_ptr<T>: dueño único de un recurso. No se puede copiar, solo mover.\n• shared_ptr<T>: dueño compartido, cuenta referencias internamente. Se libera cuando el último shared_ptr desaparece.\n\nRegla moderna de C++: evitá new/delete manuales cuando puedas usar smart pointers. Son igual de eficientes y muchísimo más seguros.",
        "ejemplo": '#include <iostream>\n#include <memory>\n#include <vector>\nusing namespace std;\n\nclass Recurso {\n    string nombre;\npublic:\n    Recurso(string n) : nombre(n) { cout << "Creando recurso: " << nombre << endl; }\n    ~Recurso() { cout << "Liberando recurso: " << nombre << endl; }\n    void usar() { cout << "Usando: " << nombre << endl; }\n};\n\nint main() {\n    // Memoria dinámica clásica (hay que acordarse del delete)\n    int* clasico = new int(42);\n    cout << "Clasico: " << *clasico << endl;\n    delete clasico; // si te olvidás esto, memory leak\n    \n    int* arrClasico = new int[5]{1, 2, 3, 4, 5};\n    delete[] arrClasico; // con corchetes para arrays\n    \n    // unique_ptr: dueño único, se libera solo al salir de scope\n    {\n        unique_ptr<Recurso> r1 = make_unique<Recurso>("A");\n        r1->usar();\n        // r1 se destruye automáticamente acá, sin delete manual\n    }\n    cout << "--- fin del scope de r1 ---" << endl;\n    \n    // shared_ptr: cuenta referencias\n    shared_ptr<Recurso> r2 = make_shared<Recurso>("B");\n    cout << "Contador de referencias: " << r2.use_count() << endl; // 1\n    {\n        shared_ptr<Recurso> r3 = r2; // comparten el mismo recurso\n        cout << "Contador de referencias: " << r2.use_count() << endl; // 2\n    } // r3 se destruye, pero el recurso sigue vivo porque r2 aún existe\n    cout << "Contador de referencias: " << r2.use_count() << endl; // 1\n    \n    // Vector de smart pointers (patrón muy común)\n    vector<unique_ptr<Recurso>> recursos;\n    recursos.push_back(make_unique<Recurso>("C"));\n    recursos.push_back(make_unique<Recurso>("D"));\n    for (auto& r : recursos) r->usar();\n    \n    return 0; // todos los recursos restantes se liberan solos acá\n}',
        "ejercicio": "1. Creá una clase Contador con constructor y destructor que impriman mensajes\n2. Creá 3 objetos con make_unique y guardalos en un vector<unique_ptr<Contador>>\n3. Creá dos shared_ptr al mismo objeto y mostrá use_count() en distintos puntos del programa\n4. Explicá con comentarios en qué momento se libera cada recurso (dónde ves los mensajes del destructor en la salida)",
        "pista": "make_unique<Contador>() y make_shared<Contador>() son más seguros que new porque no dejan un puntero crudo suelto. use_count() solo existe en shared_ptr, no en unique_ptr."
    },
    {
        "id": 19, "bloque": "Memoria y bajo nivel", "titulo": "Cómo funciona una computadora por dentro",
        "descripcion": "Compilación, CPU y memoria explicados con C++", "xp": 125,
        "teoria": "Programar en C++ te obliga a entender más de cerca cómo funciona una computadora, a diferencia de lenguajes interpretados como Python.\n\nEl proceso de compilación tiene 4 etapas:\n1. Preprocesado: reemplaza #include y #define por su contenido real (expande el código antes de compilar)\n2. Compilación: traduce el código C++ a código ensamblador (assembly), específico del procesador\n3. Ensamblado: convierte el assembly a código objeto (binario, .o u .obj)\n4. Enlazado (linking): une tu código objeto con las librerías necesarias (como iostream) para generar el ejecutable final\n\nCPU y memoria:\n• La CPU ejecuta instrucciones una por una (o en paralelo con varios núcleos), a una velocidad medida en GHz (ciclos por segundo)\n• La RAM guarda datos temporalmente mientras el programa corre; se borra al apagar\n• Registros: memoria ultra rápida dentro de la CPU misma, donde se guardan los valores que se están operando en ese instante\n• Caché (L1, L2, L3): memoria intermedia entre CPU y RAM, más rápida que RAM pero más chica\n\nCompilado vs interpretado: C++ se compila a código máquina nativo ANTES de ejecutarse (rápido, pero hay que recompilar en cada cambio). Python se interpreta línea por línea en tiempo de ejecución (más lento, pero más flexible).\n\nEndianness, representación binaria de números, y el hecho de que un int ocupa 4 bytes fijos son todas consecuencias directas de programar cerca del hardware.",
        "ejemplo": '#include <iostream>\nusing namespace std;\n\nint main() {\n    // sizeof() te muestra cuántos bytes ocupa cada tipo en memoria\n    cout << "Tamano de tipos en esta maquina:" << endl;\n    cout << "  char: " << sizeof(char) << " bytes" << endl;\n    cout << "  int: " << sizeof(int) << " bytes" << endl;\n    cout << "  long long: " << sizeof(long long) << " bytes" << endl;\n    cout << "  float: " << sizeof(float) << " bytes" << endl;\n    cout << "  double: " << sizeof(double) << " bytes" << endl;\n    cout << "  bool: " << sizeof(bool) << " bytes" << endl;\n    \n    // Un int tiene un rango limitado porque ocupa 4 bytes fijos = 32 bits\n    int maximo = 2147483647;\n    cout << "\\nint maximo: " << maximo << endl;\n    cout << "int maximo + 1 (overflow): " << maximo + 1 << endl; // da negativo!\n    \n    // Representación en memoria: un char es en realidad un número (código ASCII/UTF)\n    char letra = \'A\';\n    cout << "\\nLa letra \'A\' es en realidad el numero: " << (int)letra << endl; // 65\n    \n    // Direcciones de memoria reales de tus variables\n    int x = 10;\n    cout << "\\nLa variable x vive en la direccion: " << &x << endl;\n    cout << "Cada int ocupa " << sizeof(x) << " bytes a partir de esa direccion" << endl;\n    \n    // Medir cuánto tarda la CPU en hacer un millón de operaciones\n    long suma = 0;\n    for (long i = 0; i < 1000000; i++) suma += i;\n    cout << "\\nSuma de 1 a 999999: " << suma << endl;\n    \n    return 0;\n}',
        "ejercicio": "1. Usá sizeof() para mostrar el tamaño de todos los tipos básicos de C++ en tu máquina\n2. Provocá y explicá un overflow de int sumándole 1 al valor máximo (INT_MAX de <climits>)\n3. Convertí varios caracteres a su valor ASCII con (int) y viceversa un número a char\n4. Escribí un comentario explicando, en tus palabras, qué pasa desde que ejecutás 'g++ programa.cpp' hasta que ves el resultado en pantalla",
        "pista": "#include <climits> te da INT_MAX e INT_MIN. Para convertir: char c = 66; cout << (int)c; — int n = 67; cout << (char)n;"
    },
    {
        "id": 20, "bloque": "C++ moderno", "titulo": "Templates genéricos",
        "descripcion": "Funciones y clases que funcionan con cualquier tipo", "xp": 175,
        "teoria": "Los templates permiten escribir código GENÉRICO: una sola función o clase que funciona con múltiples tipos de datos, sin duplicar código. Es la base de toda la STL (vector<T>, map<K,V>, etc. son templates).\n\nFunción template:\ntemplate <typename T>\nT maximo(T a, T b) {\n    return a > b ? a : b;\n}\nSirve para int, double, string, o cualquier tipo que soporte el operador >.\n\nClase template:\ntemplate <typename T>\nclass Caja {\n    T contenido;\n public:\n    void guardar(T valor) { contenido = valor; }\n    T obtener() { return contenido; }\n};\nSe instancia como Caja<int> o Caja<string>.\n\nEl compilador genera código específico para cada tipo con el que usás el template (esto se llama 'instanciación'), en tiempo de compilación — por eso no hay costo de rendimiento en runtime, a diferencia de otros mecanismos de genericidad.\n\nPodés usar múltiples parámetros de tipo: template <typename K, typename V>, como hace std::map<K, V> internamente.",
        "ejemplo": '#include <iostream>\n#include <string>\n#include <vector>\nusing namespace std;\n\n// Función template\ntemplate <typename T>\nT maximo(T a, T b) {\n    return a > b ? a : b;\n}\n\ntemplate <typename T>\nvoid imprimirArray(T arr[], int n) {\n    for (int i = 0; i < n; i++) cout << arr[i] << " ";\n    cout << endl;\n}\n\n// Clase template\ntemplate <typename T>\nclass Pila {\n    vector<T> elementos;\npublic:\n    void push(T valor) { elementos.push_back(valor); }\n    T pop() {\n        T tope = elementos.back();\n        elementos.pop_back();\n        return tope;\n    }\n    bool vacia() const { return elementos.empty(); }\n    int tamano() const { return elementos.size(); }\n};\n\n// Template con dos tipos\ntemplate <typename K, typename V>\nclass Par {\n    K clave;\n    V valor;\npublic:\n    Par(K k, V v) : clave(k), valor(v) {}\n    void mostrar() const {\n        cout << clave << " -> " << valor << endl;\n    }\n};\n\nint main() {\n    cout << maximo(5, 8) << endl;         // 8 (int)\n    cout << maximo(3.5, 2.1) << endl;     // 3.5 (double)\n    cout << maximo(string("ana"), string("bob")) << endl; // bob (string)\n    \n    int enteros[] = {1, 2, 3, 4};\n    double decimales[] = {1.1, 2.2, 3.3};\n    imprimirArray(enteros, 4);\n    imprimirArray(decimales, 3);\n    \n    Pila<int> pilaEnteros;\n    pilaEnteros.push(10);\n    pilaEnteros.push(20);\n    cout << "Tope: " << pilaEnteros.pop() << endl; // 20\n    \n    Pila<string> pilaTextos;\n    pilaTextos.push("hola");\n    pilaTextos.push("mundo");\n    cout << "Tope: " << pilaTextos.pop() << endl; // mundo\n    \n    Par<string, int> edad("Ana", 25);\n    edad.mostrar(); // Ana -> 25\n    \n    return 0;\n}',
        "ejercicio": "1. Escribí una función template minimo(T a, T b) equivalente a maximo pero para el menor\n2. Escribí una función template esArrayOrdenado(T arr[], int n) que funcione con int, double o char\n3. Extendé la clase Pila<T> con un método T top() const que devuelva el tope sin sacarlo\n4. Probá tu Pila<T> con al menos dos tipos distintos (por ejemplo Pila<double> y Pila<char>)",
        "pista": "esArrayOrdenado: for(int i=0;i<n-1;i++) if(arr[i]>arr[i+1]) return false; return true; — funciona igual sin importar el tipo T porque solo usa el operador >."
    },
    {
        "id": 21, "bloque": "C++ moderno", "titulo": "Manejo de excepciones",
        "descripcion": "try, catch y throw para errores robustos", "xp": 150,
        "teoria": "Las excepciones son el mecanismo de C++ para manejar errores en tiempo de ejecución de forma controlada, en vez de que el programa crashee o siga con datos inválidos.\n\nSintaxis:\ntry {\n    // código que puede fallar\n    throw runtime_error(\"mensaje\");\n} catch (const runtime_error& e) {\n    // manejo específico\n} catch (const exception& e) {\n    // manejo genérico (captura cualquier excepción estándar)\n} catch (...) {\n    // captura CUALQUIER cosa, incluso tipos no estándar\n}\n\nExcepciones estándar comunes (<stdexcept>):\n• runtime_error — error genérico en tiempo de ejecución\n• invalid_argument — argumento inválido a una función\n• out_of_range — acceso fuera de rango (ej: vector.at(i) con i inválido)\n• logic_error — error de lógica del programa\n\nBuena práctica: capturá por referencia const (const exception& e) para evitar copias innecesarias.\n\nExcepciones personalizadas: podés crear tu propia clase heredando de std::exception y sobreescribiendo el método what().\n\nOjo con el rendimiento: las excepciones son para casos EXCEPCIONALES, no para control de flujo normal (por ejemplo, no las uses para validar un formulario campo por campo en un loop).",
        "ejemplo": '#include <iostream>\n#include <stdexcept>\n#include <vector>\nusing namespace std;\n\ndouble dividir(double a, double b) {\n    if (b == 0) {\n        throw runtime_error("No se puede dividir por cero");\n    }\n    return a / b;\n}\n\n// Excepción personalizada\nclass SaldoInsuficienteError : public exception {\n    string mensaje;\npublic:\n    SaldoInsuficienteError(double faltante) {\n        mensaje = "Faltan $" + to_string(faltante) + " para completar la operacion";\n    }\n    const char* what() const noexcept override {\n        return mensaje.c_str();\n    }\n};\n\nvoid retirar(double saldo, double monto) {\n    if (monto > saldo) {\n        throw SaldoInsuficienteError(monto - saldo);\n    }\n    cout << "Retiro exitoso de $" << monto << endl;\n}\n\nint main() {\n    // Básico\n    try {\n        cout << dividir(10, 2) << endl; // 5\n        cout << dividir(10, 0) << endl; // lanza excepcion\n    } catch (const runtime_error& e) {\n        cout << "Error capturado: " << e.what() << endl;\n    }\n    \n    // Acceso fuera de rango con vector.at()\n    vector<int> v = {1, 2, 3};\n    try {\n        cout << v.at(10) << endl; // lanza out_of_range\n    } catch (const out_of_range& e) {\n        cout << "Fuera de rango: " << e.what() << endl;\n    }\n    \n    // Excepción personalizada\n    try {\n        retirar(100, 500);\n    } catch (const SaldoInsuficienteError& e) {\n        cout << "Error de saldo: " << e.what() << endl;\n    }\n    \n    // catch genérico\n    try {\n        throw invalid_argument("dato invalido");\n    } catch (const exception& e) {\n        cout << "Excepcion generica: " << e.what() << endl;\n    }\n    \n    cout << "El programa sigue ejecutandose normalmente" << endl;\n    return 0;\n}',
        "ejercicio": "1. Escribí una función raizCuadrada(double x) que lance invalid_argument si x es negativo\n2. Creá una excepción personalizada EdadInvalidaError con un mensaje descriptivo\n3. Escribí una función validarEdad(int edad) que la lance si edad < 0 o edad > 120\n4. Envolvé llamadas a ambas funciones en try/catch con múltiples bloques catch, probando casos válidos e inválidos",
        "pista": "throw invalid_argument(\"x no puede ser negativo\"); — para tu excepción: class EdadInvalidaError : public exception { ... const char* what() const noexcept override { return mensaje.c_str(); } };"
    },
    {
        "id": 22, "bloque": "C++ moderno", "titulo": "Expresiones regulares",
        "descripcion": "Validá y extraé texto con la librería regex", "xp": 150,
        "teoria": "Las expresiones regulares (regex) son patrones que describen conjuntos de strings, usados para validar formatos, buscar coincidencias o extraer partes de un texto. C++ las incluye en <regex>.\n\nClases principales:\n• regex — representa el patrón compilado\n• regex_match(str, patron) — true si TODO el string coincide con el patrón\n• regex_search(str, match, patron) — busca la PRIMERA coincidencia dentro del string\n• regex_replace(str, patron, reemplazo) — reemplaza coincidencias\n\nSintaxis básica de patrones (compartida con casi todos los lenguajes):\n• \\\\d — un dígito, \\\\w — letra/número/_, \\\\s — espacio\n• + — uno o más, * — cero o más, ? — cero o uno\n• {n,m} — entre n y m repeticiones\n• [abc] — cualquiera de esos caracteres, [^abc] — ninguno de esos\n• ^ — inicio de string, $ — fin de string\n• () — grupo de captura, para extraer partes específicas\n\nEjemplos de patrones típicos:\n• Email simple: \\\\w+@\\\\w+\\\\.\\\\w+\n• Solo números: ^\\\\d+$\n• Teléfono con guiones: \\\\d{3}-\\\\d{3}-\\\\d{4}",
        "ejemplo": '#include <iostream>\n#include <regex>\n#include <string>\nusing namespace std;\n\nint main() {\n    // regex_match: valida el string COMPLETO\n    regex patronEmail(R"(\\w+@\\w+\\.\\w+)");\n    string email1 = "ana@mail.com";\n    string email2 = "no es un email";\n    \n    cout << boolalpha;\n    cout << "Email 1 valido: " << regex_match(email1, patronEmail) << endl; // true\n    cout << "Email 2 valido: " << regex_match(email2, patronEmail) << endl; // false\n    \n    // regex_search: busca coincidencia dentro del texto\n    string texto = "Mi telefono es 351-555-1234, llamame";\n    regex patronTelefono(R"(\\d{3}-\\d{3}-\\d{4})");\n    smatch resultado;\n    if (regex_search(texto, resultado, patronTelefono)) {\n        cout << "Telefono encontrado: " << resultado[0] << endl;\n    }\n    \n    // Grupos de captura\n    string fecha = "Hoy es 2026-08-20";\n    regex patronFecha(R"((\\d{4})-(\\d{2})-(\\d{2}))");\n    smatch matchFecha;\n    if (regex_search(fecha, matchFecha, patronFecha)) {\n        cout << "Fecha completa: " << matchFecha[0] << endl;\n        cout << "Anio: " << matchFecha[1] << ", Mes: " << matchFecha[2] << ", Dia: " << matchFecha[3] << endl;\n    }\n    \n    // regex_replace\n    string original = "Contacto: 351-111-2222 o 351-333-4444";\n    string censurado = regex_replace(original, patronTelefono, "***-***-****");\n    cout << "Censurado: " << censurado << endl;\n    \n    // Validar solo dígitos\n    regex soloDigitos(R"(^\\d+$)");\n    cout << "\'12345\' es solo digitos: " << regex_match(string("12345"), soloDigitos) << endl;\n    cout << "\'123a5\' es solo digitos: " << regex_match(string("123a5"), soloDigitos) << endl;\n    \n    return 0;\n}',
        "ejercicio": "1. Escribí un patrón que valide contraseñas: al menos 8 caracteres, al menos una mayúscula y un número (podés usar múltiples regex_search en combinación)\n2. Escribí una función extraerNumeros(string texto) que devuelva un vector<string> con todos los números encontrados en un texto usando sregex_iterator\n3. Usá regex_replace para anonimizar todos los emails de un texto reemplazándolos por \"[EMAIL OCULTO]\"\n4. Probá cada función con al menos 3 casos distintos",
        "pista": "Para extraer todos los matches: sregex_iterator it(texto.begin(), texto.end(), patron), fin; for(; it != fin; ++it) resultados.push_back(it->str());"
    },
    {
        "id": 23, "bloque": "C++ moderno", "titulo": "Fechas y tiempos con chrono",
        "descripcion": "Medí duraciones y trabajá con tiempo real", "xp": 125,
        "teoria": "La librería <chrono> (desde C++11) maneja tiempo de forma type-safe: duraciones, puntos en el tiempo, y relojes del sistema.\n\nConceptos principales:\n• Relojes (clocks): system_clock (hora real del sistema, puede ajustarse), steady_clock (siempre avanza, ideal para medir duraciones porque no se ve afectado por cambios de hora), high_resolution_clock (la mayor precisión disponible)\n• time_point: un instante específico en el tiempo\n• duration: la diferencia entre dos time_points, expresada en una unidad (segundos, milisegundos, etc.)\n\nMedir cuánto tarda un bloque de código (patrón muy común):\nauto inicio = high_resolution_clock::now();\n// ... código a medir ...\nauto fin = high_resolution_clock::now();\nauto duracion = duration_cast<milliseconds>(fin - inicio);\n\nObtener la fecha/hora actual del sistema y convertirla a texto legible requiere pasar por time_t y las funciones de C (<ctime>), ya que chrono se enfoca en duraciones precisas más que en calendarios — es un poco más verboso que en Python o JS, pero es el estándar en C++.",
        "ejemplo": '#include <iostream>\n#include <chrono>\n#include <ctime>\n#include <thread>\nusing namespace std;\nusing namespace std::chrono;\n\nlong sumaLenta(long n) {\n    long suma = 0;\n    for (long i = 0; i < n; i++) suma += i;\n    return suma;\n}\n\nint main() {\n    // Medir cuánto tarda una operación\n    auto inicio = high_resolution_clock::now();\n    long resultado = sumaLenta(50000000);\n    auto fin = high_resolution_clock::now();\n    \n    auto duracionMs = duration_cast<milliseconds>(fin - inicio);\n    cout << "Resultado: " << resultado << endl;\n    cout << "Tardo: " << duracionMs.count() << " ms" << endl;\n    \n    // Fecha y hora actual del sistema\n    auto ahora = system_clock::now();\n    time_t ahoraTiempo = system_clock::to_time_t(ahora);\n    cout << "Fecha y hora actual: " << ctime(&ahoraTiempo);\n    \n    // Trabajar con duraciones explícitas\n    seconds cincoSegundos(5);\n    minutes dosMinutos(2);\n    auto totalSegundos = duration_cast<seconds>(dosMinutos) + cincoSegundos;\n    cout << "2 minutos + 5 segundos = " << totalSegundos.count() << " segundos" << endl;\n    \n    // Comparar duraciones\n    milliseconds unaOperacion(150);\n    milliseconds otraOperacion(300);\n    if (unaOperacion < otraOperacion) {\n        cout << "La primera operacion es mas rapida" << endl;\n    }\n    \n    return 0;\n}',
        "ejercicio": "1. Escribí una función medirTiempo que reciba una función (o un bloque de código) y muestre cuánto tardó en ejecutarse, en milisegundos\n2. Compará el tiempo de tu bubbleSort del módulo de ordenamiento contra std::sort con un vector de 5000 elementos\n3. Convertí 3 horas, 25 minutos y 10 segundos todo a segundos usando duration_cast\n4. Mostrá la fecha y hora actual del sistema con ctime",
        "pista": "duration_cast<seconds>(hours(3) + minutes(25) + seconds(10)).count(); — para medir cualquier bloque: metelo entre high_resolution_clock::now() antes y después, y restá."
    },
    {
        "id": 24, "bloque": "C++ moderno", "titulo": "Tablas hash desde cero",
        "descripcion": "Implementá una hash table con manejo de colisiones, sin usar la STL", "xp": 175,
        "teoria": "unordered_map de la STL es una tabla hash lista para usar, pero entender CÓMO funciona por dentro es clave para saber cuándo confiar en ella y cuándo puede fallar (por ejemplo, con una mala función de hash).\n\nIdea central: una función de hash convierte una clave (string, int, lo que sea) en un ÍNDICE dentro de un array. Guardás el valor en ese índice, y para buscarlo después volvés a calcular el hash de la clave y vas directo a esa posición — por eso el acceso es O(1) promedio, en vez de O(n) como recorrer una lista.\n\nColisiones: dos claves distintas pueden generar el MISMO índice (es matemáticamente inevitable con un array de tamaño finito). La estrategia más común para resolverlo es chaining (encadenamiento): cada posición del array no guarda un solo valor, sino una LISTA de pares clave-valor — si dos claves colisionan, ambas conviven en la misma lista de esa posición.\n\nFunción de hash: tiene que ser rápida de calcular y distribuir las claves lo más uniformemente posible entre los índices disponibles. Una función de hash mala (que concentra muchas claves en pocos índices) degrada el rendimiento de O(1) a O(n) en el peor caso.\n\nFactor de carga (load factor): la relación entre cantidad de elementos guardados y tamaño del array. Cuando crece demasiado (muchos elementos para pocos índices), las tablas hash reales se REDIMENSIONAN (rehashing): crean un array más grande y reinsertan todo — esto es lo que hace unordered_map automáticamente por vos.",
        "ejemplo": '#include <iostream>\n#include <vector>\n#include <list>\n#include <string>\nusing namespace std;\n\nclass TablaHash {\n    static const int CAPACIDAD = 16;\n    vector<list<pair<string, int>>> baldes; // "chaining": cada posición es una lista\n\n    int hash(const string& clave) const {\n        unsigned long suma = 0;\n        for (char c : clave) {\n            suma = suma * 31 + c; // función de hash simple pero razonable\n        }\n        return suma % CAPACIDAD;\n    }\n\npublic:\n    TablaHash() : baldes(CAPACIDAD) {}\n\n    void insertar(const string& clave, int valor) {\n        int indice = hash(clave);\n        for (auto& par : baldes[indice]) {\n            if (par.first == clave) {\n                par.second = valor; // ya existe, actualiza\n                return;\n            }\n        }\n        baldes[indice].push_back({clave, valor}); // nueva clave en este balde\n    }\n\n    bool buscar(const string& clave, int& valorSalida) const {\n        int indice = hash(clave);\n        for (const auto& par : baldes[indice]) {\n            if (par.first == clave) {\n                valorSalida = par.second;\n                return true;\n            }\n        }\n        return false;\n    }\n\n    bool eliminar(const string& clave) {\n        int indice = hash(clave);\n        auto& balde = baldes[indice];\n        for (auto it = balde.begin(); it != balde.end(); ++it) {\n            if (it->first == clave) {\n                balde.erase(it);\n                return true;\n            }\n        }\n        return false;\n    }\n\n    void mostrarDistribucion() const {\n        for (int i = 0; i < CAPACIDAD; i++) {\n            cout << "Balde " << i << ": " << baldes[i].size() << " elementos" << endl;\n        }\n    }\n};\n\nint main() {\n    TablaHash tabla;\n    tabla.insertar("nombre", 1);\n    tabla.insertar("edad", 2);\n    tabla.insertar("ciudad", 3);\n    tabla.insertar("nombre", 100); // actualiza el valor existente\n\n    int valor;\n    if (tabla.buscar("edad", valor)) cout << "edad -> " << valor << endl;\n    if (tabla.buscar("nombre", valor)) cout << "nombre -> " << valor << endl;\n\n    cout << "Existe \'pais\': " << boolalpha << tabla.buscar("pais", valor) << endl;\n\n    tabla.eliminar("ciudad");\n    cout << "Existe \'ciudad\' despues de eliminar: " << tabla.buscar("ciudad", valor) << endl;\n\n    return 0;\n}',
        "ejercicio": "1. Agregá un método size() que cuente el total de elementos en toda la tabla (sumando todos los baldes)\n2. Insertá 50 claves distintas y usá mostrarDistribucion() para ver qué tan pareja quedó la distribución entre los 16 baldes\n3. Escribí una función de hash DELIBERADAMENTE mala (por ejemplo, que solo use el primer carácter de la clave) e insertá las mismas 50 claves — comparé la distribución contra la función de hash original\n4. Explicá en un comentario qué pasaría con el rendimiento de búsqueda si TODAS las claves cayeran en el mismo balde",
        "pista": "Con una función de hash mala, todas las búsquedas se degradan a O(n) porque terminás recorriendo una lista larga en un solo balde, en vez de acceder directo — es exactamente el problema que una buena función de hash evita."
    },
    {
        "id": 25, "bloque": "C++ moderno", "titulo": "Move semantics y rvalue references",
        "descripcion": "Evitá copias innecesarias con std::move y constructores de movimiento", "xp": 150,
        "teoria": "Antes de C++11, copiar un objeto grande (un vector con un millón de elementos, por ejemplo) siempre implicaba duplicar TODA su memoria, incluso cuando el original ya no se iba a usar más. Move semantics resuelve esto: en vez de copiar, TRANSFIERE la propiedad de los recursos internos de un objeto a otro, dejando al original vacío.\n\nlvalue vs rvalue: un lvalue es algo que tiene un nombre y una dirección de memoria estable (una variable). Un rvalue es un valor TEMPORAL sin nombre, que va a desaparecer pronto (el resultado de una expresión, un literal, el retorno de una función). Los rvalues son candidatos perfectos para 'robarles' sus recursos en vez de copiarlos, porque de todas formas se van a destruir.\n\nRvalue reference (T&&): un tipo de referencia que solo puede enlazar con rvalues. Se usa para escribir constructores y operadores de movimiento.\n\nConstructor de movimiento: en vez de copiar los datos internos, se 'roba' el puntero/recurso del objeto original y lo deja en un estado vacío pero válido (por ejemplo, un puntero a nullptr).\n\nstd::move(x): NO mueve nada por sí solo — es un CAST que le dice al compilador 'tratá a x como un rvalue', habilitando que se use el constructor/operador de movimiento en vez del de copia. Después de hacer std::move(x), x queda en un estado válido pero indeterminado — no deberías seguir usando su valor (aunque sí podés reasignarle uno nuevo o destruirlo).\n\n¿Por qué importa? std::vector, std::string y la mayoría de los contenedores de la STL ya implementan move semantics — por eso devolver un vector grande de una función, o hacer push_back de un objeto temporal, es mucho más barato en C++ moderno que en C++ clásico.",
        "ejemplo": '#include <iostream>\n#include <vector>\n#include <utility>\nusing namespace std;\n\nclass Buffer {\n    int* datos;\n    size_t tamano;\npublic:\n    Buffer(size_t n) : tamano(n) {\n        datos = new int[n];\n        cout << "Constructor normal: reservando " << n << " ints" << endl;\n    }\n\n    // Constructor de COPIA: duplica toda la memoria\n    Buffer(const Buffer& otro) : tamano(otro.tamano) {\n        datos = new int[tamano];\n        for (size_t i = 0; i < tamano; i++) datos[i] = otro.datos[i];\n        cout << "Constructor de COPIA: duplicando " << tamano << " ints (caro)" << endl;\n    }\n\n    // Constructor de MOVIMIENTO: roba el puntero, no copia nada\n    Buffer(Buffer&& otro) noexcept : datos(otro.datos), tamano(otro.tamano) {\n        otro.datos = nullptr; // el original queda vacío pero válido\n        otro.tamano = 0;\n        cout << "Constructor de MOVIMIENTO: robando el puntero (barato)" << endl;\n    }\n\n    ~Buffer() {\n        delete[] datos; // delete[] en nullptr no hace nada, es seguro\n    }\n\n    size_t size() const { return tamano; }\n};\n\nBuffer crearBufferGrande() {\n    Buffer b(1000000);\n    return b; // el compilador aplica move automáticamente al retornar\n}\n\nint main() {\n    cout << "--- Copia explícita ---" << endl;\n    Buffer original(5);\n    Buffer copia = original; // llama al constructor de COPIA\n\n    cout << "\\n--- Movimiento explícito con std::move ---" << endl;\n    Buffer origen(5);\n    Buffer destino = std::move(origen); // llama al constructor de MOVIMIENTO\n    cout << "origen.size() despues de move: " << origen.size() << " (quedo vacio)" << endl;\n\n    cout << "\\n--- Retornar de una función (move automático) ---" << endl;\n    Buffer resultado = crearBufferGrande(); // NO copia el millón de ints\n\n    cout << "\\n--- push_back con std::move en un vector ---" << endl;\n    vector<Buffer> buffers;\n    Buffer temp(10);\n    buffers.push_back(std::move(temp)); // mueve en vez de copiar\n\n    return 0;\n}',
        "ejercicio": "1. Agregá a la clase Buffer un operador de asignación de movimiento (Buffer& operator=(Buffer&& otro) noexcept)\n2. Creá una función intercambiar(Buffer& a, Buffer& b) que use std::move para intercambiar el contenido de dos Buffers SIN copiar ningún dato\n3. Medí con chrono la diferencia de tiempo entre insertar 1000 Buffers grandes en un vector con push_back(copia) vs push_back(std::move(...))\n4. Explicá en un comentario por qué, después de std::move(origen), NO deberías seguir leyendo origen.size() esperando el valor original",
        "pista": "El operador de movimiento es como el constructor de movimiento pero para asignación (=): primero liberá tus propios recursos actuales (delete[] datos), después robá los del otro, y siempre verificá que no sea auto-asignación (if (this != &otro))."
    },
    {
        "id": 26, "bloque": "Proyecto", "titulo": "Sistema completo",
        "descripcion": "Integrá todo en un sistema de gestión", "xp": 200,
        "teoria": "En este módulo final construirás un sistema completo que integra todos los conceptos:\n• Clases con herencia y polimorfismo\n• Vectores y mapas de STL\n• Funciones con referencias\n• Manejo de entrada/salida\n• Algoritmos de STL\n\nEl sistema es un Gestor de Biblioteca con:\n• Clase base Item con titulo, autor, año, disponible\n• Clase Libro (hereda de Item): ISBN, género, páginas\n• Clase Revista (hereda de Item): número, volumen\n• Clase Biblioteca: gestiona la colección\n• Operaciones: agregar, buscar, prestar, devolver, reportes\n\nConceptos avanzados usados:\n• Herencia pública\n• Métodos virtuales (polimorfismo)\n• Smart pointers (shared_ptr) para manejo seguro de memoria\n• Algoritmos de STL (sort, find_if)",
        "ejemplo": '#include <iostream>\n#include <vector>\n#include <string>\n#include <algorithm>\n#include <memory>\nusing namespace std;\n\nclass Item {\nprotected:\n    string titulo, autor;\n    int anio;\n    bool disponible;\npublic:\n    Item(string t, string a, int y)\n        : titulo(t), autor(a), anio(y), disponible(true) {}\n    virtual ~Item() = default;\n    \n    virtual void mostrar() const = 0; // método abstracto\n    string getTitulo() const { return titulo; }\n    bool isDisponible() const { return disponible; }\n    void prestar() { disponible = false; }\n    void devolver() { disponible = true; }\n};\n\nclass Libro : public Item {\n    string isbn, genero;\n    int paginas;\npublic:\n    Libro(string t, string a, int y, string isbn, string g, int p)\n        : Item(t, a, y), isbn(isbn), genero(g), paginas(p) {}\n    \n    void mostrar() const override {\n        cout << "[LIBRO] " << titulo << " - " << autor\n             << " (" << anio << ") | " << paginas << " págs\"\n             << " | " << (disponible ? "Disponible" : "Prestado") << endl;\n    }\n};\n\nclass Biblioteca {\n    vector<shared_ptr<Item>> catalogo;\npublic:\n    void agregar(shared_ptr<Item> item) {\n        catalogo.push_back(item);\n    }\n    \n    void mostrarTodo() const {\n        cout << "=== Catálogo (" << catalogo.size() << " items) ===" << endl;\n        for (const auto& item : catalogo) item->mostrar();\n    }\n    \n    bool prestar(const string& titulo) {\n        auto it = find_if(catalogo.begin(), catalogo.end(),\n            [&titulo](const shared_ptr<Item>& i) {\n                return i->getTitulo() == titulo && i->isDisponible();\n            });\n        if (it == catalogo.end()) return false;\n        (*it)->prestar();\n        return true;\n    }\n};\n\nint main() {\n    Biblioteca bib;\n    bib.agregar(make_shared<Libro>("El Principito","Saint-Exupéry",1943,"978-0","Ficción",96));\n    bib.agregar(make_shared<Libro>("Clean Code","Robert Martin",2008,"978-1","Técnico",431));\n    bib.mostrarTodo();\n    bib.prestar("El Principito");\n    cout << "\\nDespués de prestar:" << endl;\n    bib.mostrarTodo();\n    return 0;\n}',
        "ejercicio": "Extendé el sistema de Biblioteca:\n1. Agregá clase Revista que hereda de Item con número y volumen\n2. Agregá método buscarPorAutor(string) que devuelva vector<shared_ptr<Item>>\n3. Agregá método reporteEstadisticas() que muestre: total items, disponibles, prestados, % disponibilidad\n4. Agregá un menú interactivo con while + switch para usar el sistema",
        "pista": "Para buscarPorAutor: usa copy_if con lambda que compare autor. Para estadísticas: count_if(catalogo.begin(), catalogo.end(), [](auto& i){ return i->isDisponible(); });"
    }
]


@router.get("/modulos/cpp")
def get_modulos_cpp():
    return MODULOS_CPP
