from fastapi import APIRouter

router = APIRouter()

MODULOS_JS = [
    {
        "id": 1, "bloque": "Fundamentos", "titulo": "Hola Mundo",
        "descripcion": "Tu primer programa en JavaScript", "xp": 50,
        "teoria": "JavaScript es el lenguaje de la web. Corre en el navegador y también en el servidor (Node.js).\n\nconsole.log() es la función equivalente a print() en Python: muestra información en la consola.\n\nAlgunas diferencias clave con Python:\n• Las sentencias terminan con ; (opcional pero recomendado)\n• Los bloques se delimitan con {} en lugar de indentación\n• Los strings pueden ir con comillas simples, dobles o backticks (template literals)",
        "ejemplo": 'console.log("¡Hola, Mundo!");\nconsole.log("Mi primer programa en JS");\nconsole.log(2026);\nconsole.log(3.14);\nconsole.log("Suma:", 10 + 5);\n\n// También podés usar múltiples argumentos\nconsole.log("Resultado:", 100 / 4, "unidades");',
        "ejercicio": "Escribí un programa que muestre:\n1. Tu nombre\n2. El lenguaje que estás aprendiendo\n3. El resultado de 3 operaciones matemáticas distintas",
        "pista": "console.log(\"texto\") para texto. console.log(2 + 3) para operaciones. Podés combinar: console.log(\"Suma:\", 2 + 3)"
    },
    {
        "id": 2, "bloque": "Fundamentos", "titulo": "Variables: let y const",
        "descripcion": "Declaración moderna de variables en JS", "xp": 50,
        "teoria": "JavaScript tiene tres formas de declarar variables:\n• var — antigua, evitala (alcance de función, hoisting confuso)\n• let — variable que puede cambiar su valor\n• const — variable que no puede reasignarse (pero si es objeto/array, sí puede modificarse internamente)\n\nRegla simple: usá const por defecto. Si necesitás reasignar, usá let. Nunca usés var en código moderno.\n\nJavaScript tiene tipado dinámico como Python, pero a diferencia de Python, typeof permite verificar el tipo en runtime.",
        "ejemplo": '// const: no se puede reasignar\nconst PI = 3.14159;\nconst nombre = "Ana";\n\n// let: se puede reasignar\nlet edad = 25;\nedad = 26; // OK\n\n// typeof para verificar tipo\nconsole.log(typeof nombre); // "string"\nconsole.log(typeof edad);   // "number"\nconsole.log(typeof true);   // "boolean"\nconsole.log(typeof null);   // "object" (quirk histórico)\nconsole.log(typeof undefined); // "undefined"\n\n// Destructuring\nconst [x, y, z] = [1, 2, 3];\nconst { titulo, autor } = { titulo: "Python", autor: "Guido" };\nconsole.log(x, y, z);\nconsole.log(titulo, autor);',
        "ejercicio": "Declará con const y let:\n• Tu nombre, ciudad y año de nacimiento\n• Una variable edad calculada (2026 - año)\n• Mostralas con console.log()\n• Intentá reasignar un const (verás el error) y comentá esa línea",
        "pista": "const nombre = \"...\"; let edad = 2026 - añoNacimiento; — Para el error: const x = 1; x = 2; // TypeError"
    },
    {
        "id": 3, "bloque": "Fundamentos", "titulo": "Tipos de datos",
        "descripcion": "Los tipos básicos de JavaScript", "xp": 50,
        "teoria": "JavaScript tiene 8 tipos de datos:\n• string — texto: \"hola\", 'mundo', `template`\n• number — todos los números (enteros y decimales)\n• bigint — enteros enormes: 9007199254740991n\n• boolean — true o false\n• null — ausencia intencional de valor\n• undefined — variable declarada pero sin valor\n• symbol — identificador único\n• object — incluye arrays, funciones, objetos\n\nConversión de tipos:\n• Number(\"42\") → 42\n• String(42) → \"42\"\n• Boolean(0) → false\n• parseInt(\"42.7\") → 42\n• parseFloat(\"42.7\") → 42.7\n\nOjo: JS tiene coerción implícita que puede ser confusa: \"5\" + 3 = \"53\" (concatena), \"5\" - 3 = 2 (suma).",
        "ejemplo": '// Tipos básicos\nconst texto = "JavaScript";\nconst numero = 42;\nconst decimal = 3.14;\nconst booleano = true;\nconst nulo = null;\nlet indefinido;\n\nconsole.log(typeof texto);    // string\nconsole.log(typeof numero);   // number\nconsole.log(typeof booleano); // boolean\nconsole.log(typeof nulo);     // object (!)\nconsole.log(typeof indefinido); // undefined\n\n// Conversiones\nconsole.log(Number("42"));    // 42\nconsole.log(Number("abc"));   // NaN\nconsole.log(String(100));     // "100"\nconsole.log(Boolean(0));      // false\nconsole.log(Boolean(""));     // false\nconsole.log(Boolean("hola")); // true\n\n// Coerción implícita (cuidado!)\nconsole.log("5" + 3);  // "53" (string)\nconsole.log("5" - 3);  // 2 (number)\nconsole.log(5 == "5"); // true (coerción)\nconsole.log(5 === "5"); // false (sin coerción)',
        "ejercicio": "1. Creá una variable de cada tipo básico y mostrá typeof\n2. Convertí el string \"3.14\" a número con parseFloat y hacé una operación\n3. Mostrá la diferencia entre == y === con un ejemplo\n4. Mostrá qué valores son 'falsy' en JS (0, \"\", null, undefined, NaN, false)",
        "pista": "const falsy = [0, \"\", null, undefined, NaN, false]; falsy.forEach(v => console.log(v, Boolean(v)));"
    },
    {
        "id": 4, "bloque": "Fundamentos", "titulo": "Operadores",
        "descripcion": "Operadores aritméticos, de comparación y lógicos", "xp": 50,
        "teoria": "JavaScript comparte muchos operadores con otros lenguajes:\n\nAritméticos: + - * / % ** ++  --\n• ** es potencia (igual que Python)\n• ++ y -- son incremento/decremento (no existen en Python)\n\nComparación: == != === !== < > <= >=\n• == compara con coerción de tipos\n• === compara sin coerción (siempre usá ===)\n\nLógicos: && || ! ?? ??\n• && (and), || (or), ! (not)\n• ?? (nullish coalescing): devuelve el lado derecho si el izquierdo es null/undefined\n• ?. (optional chaining): accede a propiedad sin error si es null\n\nAsignación: = += -= *= /= %= **= &&= ||= ??=",
        "ejemplo": '// Aritméticos\nconsole.log(10 + 3);  // 13\nconsole.log(10 - 3);  // 7\nconsole.log(10 * 3);  // 30\nconsole.log(10 / 3);  // 3.333...\nconsole.log(10 % 3);  // 1\nconsole.log(2 ** 10); // 1024\n\nlet x = 5;\nx++;  // x = 6\nx--;  // x = 5\nx += 10; // x = 15\n\n// Comparación estricta (siempre usá ===)\nconsole.log(5 === 5);    // true\nconsole.log(5 === "5");  // false\nconsole.log(5 !== "5");  // true\n\n// Lógicos\nconsole.log(true && false); // false\nconsole.log(true || false); // true\nconsole.log(!true);         // false\n\n// Nullish coalescing\nconst valor = null ?? "default";\nconsole.log(valor); // "default"\n\n// Optional chaining\nconst user = { perfil: { nombre: "Ana" } };\nconsole.log(user?.perfil?.nombre); // "Ana"\nconsole.log(user?.email?.address); // undefined (sin error)',
        "ejercicio": "Creá variables a=15 y b=4. Calculá y mostrá todos los operadores aritméticos.\nDemostrá la diferencia entre == y === con 3 ejemplos.\nUsá ?? para dar un valor por defecto a una variable null.\nUsá optional chaining para acceder a propiedades anidadas de un objeto.",
        "pista": "const nombre = usuario?.datos?.nombre ?? \"Anónimo\"; — esto es equivalente a: nombre = (usuario && usuario.datos && usuario.datos.nombre) || \"Anónimo\""
    },
    {
        "id": 5, "bloque": "Fundamentos", "titulo": "if / else y switch",
        "descripcion": "Condicionales en JavaScript", "xp": 50,
        "teoria": "JavaScript tiene if/else similar a otros lenguajes, más switch/case para múltiples opciones.\n\nif/else:\nif (condicion) {\n    // código\n} else if (otra) {\n    // código\n} else {\n    // código\n}\n\nOperador ternario: condicion ? valorSiTrue : valorSiFalse\n\nswitch/case: útil cuando comparás una variable con muchos valores fijos.\nImportante: siempre incluí break en cada case, o el código 'cae' al siguiente case (fall-through).\n\nValores falsy en JS: false, 0, \"\", null, undefined, NaN — todo lo demás es truthy.",
        "ejemplo": '// if/else\nconst hora = 14;\nlet saludo;\nif (hora < 12) {\n    saludo = "Buenos días";\n} else if (hora < 18) {\n    saludo = "Buenas tardes";\n} else {\n    saludo = "Buenas noches";\n}\nconsole.log(saludo);\n\n// Ternario\nconst edad = 20;\nconst acceso = edad >= 18 ? "permitido" : "denegado";\nconsole.log(`Acceso: ${acceso}`);\n\n// switch\nconst dia = "lunes";\nswitch (dia) {\n    case "lunes":\n    case "martes":\n    case "miércoles":\n    case "jueves":\n    case "viernes":\n        console.log("Día laborable");\n        break;\n    case "sábado":\n    case "domingo":\n        console.log("Fin de semana");\n        break;\n    default:\n        console.log("Día inválido");\n}',
        "ejercicio": "1. Pedí un número (usá una variable fija) y determiná si es positivo, negativo o cero\n2. Usá ternario para clasificar una nota: aprobado (>=60) o reprobado\n3. Implementá un switch para los meses del año que muestre cuántos días tiene cada mes",
        "pista": "Para el switch de meses: case 1: case 3: ... console.log(\"31 días\"); break; — febrero tiene 28 o 29 días."
    },
    {
        "id": 6, "bloque": "Estructuras", "titulo": "Bucles",
        "descripcion": "for, while, forEach y otros bucles", "xp": 75,
        "teoria": "JavaScript tiene varios tipos de bucles:\n\nfor clásico: for (let i = 0; i < n; i++)\nfor...of: itera sobre valores de un iterable (arrays, strings)\nfor...in: itera sobre claves de un objeto\nwhile: mientras condición sea true\ndo...while: ejecuta al menos una vez\n.forEach(): método de arrays, acepta callback\n\nControl de flujo:\n• break — sale del bucle\n• continue — salta a siguiente iteración\n\nDiferencia clave entre for...of y for...in:\n• for...of array → valores: 1, 2, 3\n• for...in array → índices: '0', '1', '2'\n• for...in objeto → claves: 'nombre', 'edad'",
        "ejemplo": '// for clásico\nfor (let i = 0; i < 5; i++) {\n    process.stdout.write(i + " ");\n}\nconsole.log();\n\n// for...of\nconst frutas = ["manzana", "banana", "cereza"];\nfor (const fruta of frutas) {\n    console.log(fruta);\n}\n\n// for...in con objeto\nconst persona = { nombre: "Ana", edad: 25, ciudad: "BA" };\nfor (const clave in persona) {\n    console.log(`${clave}: ${persona[clave]}`);\n}\n\n// forEach con índice\nfrutas.forEach((fruta, i) => {\n    console.log(`${i + 1}. ${fruta}`);\n});\n\n// while\nlet contador = 0;\nwhile (contador < 5) {\n    contador++;\n}\nconsole.log("Contador final:", contador);\n\n// Acumular suma\nconst numeros = [1, 2, 3, 4, 5];\nlet suma = 0;\nfor (const n of numeros) {\n    suma += n;\n}\nconsole.log("Suma:", suma); // 15',
        "ejercicio": "1. Usá for clásico para imprimir la tabla de multiplicar del 7\n2. Usá for...of con una lista de países para mostrarlos numerados\n3. Usá for...in para mostrar las propiedades de un objeto persona\n4. Calculá el factorial de 10 usando while",
        "pista": "factorial: let resultado = 1; let i = 10; while (i > 0) { resultado *= i; i--; } — para numerados: .forEach((pais, i) => console.log(`${i+1}. ${pais}`))"
    },
    {
        "id": 7, "bloque": "Estructuras", "titulo": "Arrow functions",
        "descripcion": "Funciones modernas y concisas en JS", "xp": 75,
        "teoria": "Las arrow functions son una sintaxis moderna y concisa para definir funciones en JavaScript.\n\nSintaxis:\nconst nombre = (params) => { cuerpo };\n// Si es una sola expresión, podés omitir {} y return:\nconst doble = x => x * 2;\n\nDiferencias con function tradicional:\n• No tienen su propio this (heredan del contexto)\n• No tienen arguments object\n• No se pueden usar como constructores\n\nEsto las hace ideales para callbacks y métodos de arrays.\n\nClosure: una función que 'recuerda' las variables del scope donde fue creada, incluso después de que ese scope cerró.",
        "ejemplo": '// Función tradicional\nfunction sumar(a, b) {\n    return a + b;\n}\n\n// Arrow function equivalente\nconst sumarArrow = (a, b) => a + b;\n\nconsole.log(sumar(3, 4));      // 7\nconsole.log(sumarArrow(3, 4)); // 7\n\n// Un solo parámetro: sin paréntesis\nconst cuadrado = x => x ** 2;\nconsole.log(cuadrado(5)); // 25\n\n// Sin parámetros: paréntesis vacíos\nconst saludar = () => "¡Hola!";\n\n// Con cuerpo de bloque\nconst clasificar = (nota) => {\n    if (nota >= 90) return "A";\n    if (nota >= 80) return "B";\n    if (nota >= 70) return "C";\n    return "F";\n};\n\nconsole.log(clasificar(85)); // B\n\n// Closure\nfunction crearContador(inicio = 0) {\n    let cuenta = inicio;\n    return {\n        incrementar: () => ++cuenta,\n        decrementar: () => --cuenta,\n        valor: () => cuenta,\n    };\n}\n\nconst contador = crearContador(10);\nconsole.log(contador.incrementar()); // 11\nconsole.log(contador.incrementar()); // 12\nconsole.log(contador.decrementar()); // 11',
        "ejercicio": "1. Convertí estas funciones a arrow functions: función que calcula el área de un círculo, función que verifica si un string es palíndromo\n2. Creá una función generarSaludo(saludo) que retorne una función que salude con ese saludo (factory con closure)\n3. Usá arrow functions con map y filter en un array de números",
        "pista": "const esPalindromo = s => s.toLowerCase() === s.toLowerCase().split('').reverse().join(''); — const generarSaludo = saludo => nombre => `${saludo}, ${nombre}!`"
    },
    {
        "id": 8, "bloque": "Estructuras", "titulo": "Arrays: map, filter, reduce",
        "descripcion": "Programación funcional con arrays", "xp": 75,
        "teoria": "Los métodos funcionales de arrays son fundamentales en JavaScript moderno:\n\n• .map(callback) — transforma cada elemento, devuelve nuevo array\n• .filter(callback) — filtra elementos, devuelve nuevo array\n• .reduce(callback, inicial) — reduce a un único valor\n• .find(callback) — primer elemento que cumple condición\n• .findIndex(callback) — índice del primer match\n• .some(callback) — true si AL MENOS uno cumple\n• .every(callback) — true si TODOS cumplen\n• .flat() / .flatMap() — aplana arrays anidados\n• .sort(compareFn) — ordena (¡ojo: modifica el original!)\n\nEstos métodos son puros: no modifican el array original (excepto sort y splice).",
        "ejemplo": 'const numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];\n\n// map: duplicar cada número\nconst dobles = numeros.map(n => n * 2);\nconsole.log(dobles); // [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]\n\n// filter: solo pares\nconst pares = numeros.filter(n => n % 2 === 0);\nconsole.log(pares); // [2, 4, 6, 8, 10]\n\n// reduce: suma total\nconst suma = numeros.reduce((acc, n) => acc + n, 0);\nconsole.log(suma); // 55\n\n// Encadenar métodos (chaining)\nconst resultado = numeros\n    .filter(n => n % 2 === 0) // solo pares\n    .map(n => n ** 2)          // elevar al cuadrado\n    .reduce((acc, n) => acc + n, 0); // sumar\nconsole.log(resultado); // 220\n\n// Con objetos\nconst productos = [\n    { nombre: "A", precio: 100, stock: 5 },\n    { nombre: "B", precio: 50, stock: 0 },\n    { nombre: "C", precio: 200, stock: 3 },\n];\n\nconst disponibles = productos.filter(p => p.stock > 0);\nconst nombres = disponibles.map(p => p.nombre);\nconst totalValor = productos.reduce((acc, p) => acc + p.precio * p.stock, 0);\nconsole.log(nombres);\nconsole.log("Valor total:", totalValor);',
        "ejercicio": "Dado un array de estudiantes [{nombre, nota, carrera}]:\n1. Filtrá los que aprobaron (nota >= 60)\n2. Creá un array solo con los nombres de los aprobados\n3. Calculá el promedio general con reduce\n4. Encontrá el estudiante con la nota más alta\n5. Verificá si TODOS aprobaron y si ALGUNO reprobó",
        "pista": "const promedio = estudiantes.reduce((acc, e) => acc + e.nota, 0) / estudiantes.length; — const mejor = estudiantes.reduce((max, e) => e.nota > max.nota ? e : max);"
    },
    {
        "id": 9, "bloque": "Asincronía", "titulo": "Promesas y async/await",
        "descripcion": "Código asíncrono moderno en JavaScript", "xp": 100,
        "teoria": "JavaScript es single-threaded pero asíncrono. Para operaciones que toman tiempo (red, archivos, timers), usa el event loop.\n\nCallbacks (antiguo): función que se llama cuando termina.\nProblema: callback hell (anidación profunda).\n\nPromesas: objeto que representa un valor futuro.\nEstados: pending, fulfilled, rejected.\n.then() para el resultado, .catch() para errores, .finally() siempre.\n\nasync/await (moderno): sintaxis más limpia sobre promesas.\n• async: marca una función como asíncrona (devuelve Promise)\n• await: espera que una Promise se resuelva\n• Siempre envolvé await en try/catch\n\nPromise.all([p1, p2]): espera que TODAS las promesas terminen.\nPromise.race([p1, p2]): devuelve la primera que termine.",
        "ejemplo": '// Simular operación asíncrona\nconst esperar = (ms) => new Promise(resolve => setTimeout(resolve, ms));\n\nconst fetchDatos = (id) => new Promise((resolve, reject) => {\n    setTimeout(() => {\n        if (id > 0) {\n            resolve({ id, nombre: `Usuario ${id}`, activo: true });\n        } else {\n            reject(new Error("ID inválido"));\n        }\n    }, 100);\n});\n\n// Con .then()/.catch()\nfetchDatos(1)\n    .then(datos => console.log("Con then:", datos))\n    .catch(err => console.error("Error:", err.message));\n\n// Con async/await (más legible)\nasync function obtenerUsuario(id) {\n    try {\n        const usuario = await fetchDatos(id);\n        console.log("Con await:", usuario);\n        return usuario;\n    } catch (error) {\n        console.error("Error:", error.message);\n        return null;\n    }\n}\n\n// Paralelo con Promise.all\nasync function main() {\n    const [u1, u2, u3] = await Promise.all([\n        fetchDatos(1),\n        fetchDatos(2),\n        fetchDatos(3),\n    ]);\n    console.log("Todos:", u1.nombre, u2.nombre, u3.nombre);\n}\n\nmain();',
        "ejercicio": "1. Creá una función delay(ms) que retorna una Promise que se resuelve después de ms milisegundos\n2. Creá una función fetchProducto(id) que simule buscar un producto (resuelve si id>0, rechaza si no)\n3. Usá async/await con try/catch para llamarla\n4. Usá Promise.all para buscar 3 productos en paralelo y mostrá cuánto tardó en total",
        "pista": "const inicio = Date.now(); await Promise.all([...]); console.log(`Tardó ${Date.now() - inicio}ms`); — Promise.all corre en paralelo así que es más rápido que secuencial."
    },
    {
        "id": 10, "bloque": "DOM", "titulo": "DOM y eventos",
        "descripcion": "Manipulá la página web con JavaScript", "xp": 125,
        "teoria": "El DOM (Document Object Model) es la representación en árbol del HTML que JavaScript puede manipular.\n\nSeleccionar elementos:\n• document.getElementById('id')\n• document.querySelector('.clase') — primer match\n• document.querySelectorAll('div.card') — todos los matches\n\nManipular elementos:\n• elemento.textContent = 'texto'\n• elemento.innerHTML = '<b>HTML</b>'\n• elemento.classList.add/remove/toggle('clase')\n• elemento.style.color = 'red'\n• elemento.setAttribute('href', '...')\n\nCrear y agregar elementos:\n• document.createElement('div')\n• padre.appendChild(hijo)\n• padre.removeChild(hijo)\n\nEventos:\n• elemento.addEventListener('click', callback)\n• Eventos: click, input, submit, keydown, mouseover, etc.",
        "ejemplo": '// Este código funciona en el navegador\n// En Node.js se simulará la estructura\n\n// Simular DOM en Node.js para practicar la lógica\nconst elementos = {\n    contador: { valor: 0 }\n};\n\nfunction actualizarContador() {\n    elementos.contador.valor++;\n    console.log(`Contador: ${elementos.contador.valor}`);\n}\n\nfunction resetearContador() {\n    elementos.contador.valor = 0;\n    console.log("Contador reseteado a 0");\n}\n\n// Simular eventos\nconsole.log("Inicio de la app");\nactualizarContador();\nactualizarContador();\nactualizarContador();\nresetearContador();\nactualizarContador();\n\n// En el navegador real sería:\n/*\ndocument.getElementById("incrementar").addEventListener("click", () => {\n    contador++;\n    document.getElementById("display").textContent = contador;\n});\n*/\n\nconsole.log("\\n--- Manipulación de lista ---");\nconst tareas = [];\n\nfunction agregarTarea(texto) {\n    tareas.push({ id: Date.now(), texto, completada: false });\n    console.log(`Tarea agregada: "${texto}"`);\n}\n\nfunction mostrarTareas() {\n    console.log("\\nLista de tareas:");\n    tareas.forEach((t, i) => {\n        const estado = t.completada ? "[✓]" : "[ ]";\n        console.log(`${estado} ${i + 1}. ${t.texto}`);\n    });\n}\n\nagregarTarea("Aprender JavaScript");\nagregarTarea("Practicar DOM");\ntareas[0].completada = true;\nmostrarTareas();',
        "ejercicio": "Simulá una aplicación de tareas (sin DOM real ya que corremos en Node.js):\n1. Array de tareas con id, texto, completada, prioridad (alta/media/baja)\n2. Funciones: agregar, completar, eliminar, filtrarPorPrioridad\n3. Función renderizar() que muestra las tareas en consola de forma visual\n4. Simulá una serie de operaciones y mostrá el estado final",
        "pista": "function renderizar(tareas) { console.log('='.repeat(30)); tareas.forEach(t => console.log(`${t.completada ? '✓' : '○'} [${t.prioridad}] ${t.texto}`)); }"
    },
    {
        "id": 11, "bloque": "Funciones avanzadas", "titulo": "Parámetros por defecto y rest/spread",
        "descripcion": "Funciones más flexibles con valores por defecto y múltiples argumentos", "xp": 100,
        "teoria": "Las funciones modernas de JavaScript tienen tres herramientas para ser más flexibles:\n\nParámetros por defecto: si no pasás un argumento, se usa un valor por defecto.\nfunction saludar(nombre = \"invitado\") { ... }\n\nRest parameters (...): junta argumentos sueltos en un array. Debe ir al final.\nfunction sumar(...numeros) { return numeros.reduce((a,b) => a+b, 0); }\n\nSpread operator (...): expande un array u objeto en elementos sueltos. Es lo opuesto a rest, y se usa fuera de la definición de función (al llamarla, o al construir arrays/objetos nuevos).\nconst combinado = [...arr1, ...arr2];\nconst copia = { ...original, extra: 1 };\n\nOjo: rest y spread usan la misma sintaxis (...) pero el contexto define su significado: en los parámetros de una función es rest (agrupa), en una llamada o literal es spread (expande).",
        "ejemplo": 'function crearPerfil(nombre, edad = 18, ciudad = "Sin especificar") {\n    return `${nombre}, ${edad} años, vive en ${ciudad}`;\n}\n\nconsole.log(crearPerfil("Ana"));                  // Ana, 18 años, vive en Sin especificar\nconsole.log(crearPerfil("Luis", 30, "Córdoba"));  // Luis, 30 años, vive en Córdoba\n\n// Rest: junta argumentos en un array\nfunction sumarTodo(...numeros) {\n    return numeros.reduce((acc, n) => acc + n, 0);\n}\nconsole.log(sumarTodo(1, 2, 3));       // 6\nconsole.log(sumarTodo(1, 2, 3, 4, 5)); // 15\n\n// Spread: expande arrays\nconst base = [1, 2, 3];\nconst extendido = [...base, 4, 5];\nconsole.log(extendido); // [1, 2, 3, 4, 5]\n\n// Spread con objetos (copiar y sobreescribir)\nconst usuario = { nombre: "Ana", rol: "estudiante" };\nconst usuarioActualizado = { ...usuario, rol: "instructora" };\nconsole.log(usuarioActualizado); // { nombre: "Ana", rol: "instructora" }\n\n// Spread para pasar argumentos\nfunction sumarTres(a, b, c) { return a + b + c; }\nconst valores = [10, 20, 30];\nconsole.log(sumarTres(...valores)); // 60',
        "ejercicio": "1. Escribí una función crearProducto(nombre, precio, descuento = 0) que calcule el precio final\n2. Escribí una función contarPalabras(...frases) que reciba varios strings sueltos y cuente el total de palabras entre todos\n3. Usá spread para combinar dos arrays de tareas en uno solo sin duplicar\n4. Usá spread con objetos para crear una copia de un objeto configuración con un valor modificado",
        "pista": "precio final: precio - (precio * descuento / 100). Para contar palabras: frases.reduce((total, f) => total + f.split(' ').length, 0)"
    },
    {
        "id": 12, "bloque": "Funciones avanzadas", "titulo": "Closures y funciones de orden superior",
        "descripcion": "Funciones que devuelven funciones y recuerdan su contexto", "xp": 100,
        "teoria": "Una función de orden superior (higher-order function) es una función que recibe otra función como argumento, o devuelve una función como resultado. map, filter y reduce son ejemplos que ya usaste.\n\nUn closure ocurre cuando una función interna 'recuerda' las variables del scope donde fue definida, incluso después de que ese scope terminó de ejecutarse. Es la base de patrones como contadores privados, memoización y fábricas de funciones.\n\nCada vez que llamás a la función externa, se crea un nuevo closure independiente — las variables no se comparten entre llamadas distintas.\n\nUsos típicos:\n• Encapsular estado privado (sin usar clases)\n• Crear funciones configurables (currying)\n• Memoización: cachear resultados de cálculos costosos",
        "ejemplo": 'function crearBancoDeCuenta(saldoInicial) {\n    let saldo = saldoInicial; // "privado", solo accesible por closure\n    return {\n        depositar: (monto) => { saldo += monto; return saldo; },\n        retirar: (monto) => {\n            if (monto > saldo) return "Fondos insuficientes";\n            saldo -= monto;\n            return saldo;\n        },\n        consultarSaldo: () => saldo,\n    };\n}\n\nconst cuenta = crearBancoDeCuenta(100);\nconsole.log(cuenta.depositar(50));  // 150\nconsole.log(cuenta.retirar(30));    // 120\nconsole.log(cuenta.consultarSaldo()); // 120\n\n// Función de orden superior: currying\nfunction multiplicador(factor) {\n    return (numero) => numero * factor;\n}\nconst duplicar = multiplicador(2);\nconst triplicar = multiplicador(3);\nconsole.log(duplicar(5));   // 10\nconsole.log(triplicar(5));  // 15\n\n// Memoización con closure\nfunction crearMemo() {\n    const cache = {};\n    return (n) => {\n        if (n in cache) {\n            console.log(`(desde cache) ${n}`);\n            return cache[n];\n        }\n        const resultado = n * n; // cálculo "costoso"\n        cache[n] = resultado;\n        return resultado;\n    };\n}\nconst cuadradoMemo = crearMemo();\nconsole.log(cuadradoMemo(5)); // calcula\nconsole.log(cuadradoMemo(5)); // desde cache',
        "ejercicio": "1. Creá crearContador(inicio) que devuelva un objeto con incrementar(), decrementar() y valor()\n2. Creá una función de orden superior aplicarDescuento(porcentaje) que devuelva una función que aplique ese descuento a un precio\n3. Creá dos contadores independientes con crearContador y demostrá que no comparten estado entre sí\n4. Usá tu función de descuento para calcular el precio final de 3 productos distintos",
        "pista": "const contadorA = crearContador(0); const contadorB = crearContador(100); — cada llamada a crearContador genera su propia variable 'cuenta' independiente."
    },
    {
        "id": 13, "bloque": "Sintaxis moderna", "titulo": "Métodos de string y template literals",
        "descripcion": "Manipulá texto como un profesional", "xp": 75,
        "teoria": "JavaScript tiene muchos métodos útiles para trabajar con strings (son inmutables: ningún método modifica el original, todos devuelven un string nuevo):\n\n• .length — cantidad de caracteres\n• .toUpperCase() / .toLowerCase()\n• .trim() / .trimStart() / .trimEnd() — elimina espacios\n• .includes(texto) — true/false si contiene el texto\n• .startsWith() / .endsWith()\n• .slice(inicio, fin) — extrae una porción (acepta índices negativos)\n• .split(separador) — divide en array\n• .replace(viejo, nuevo) / .replaceAll(viejo, nuevo)\n• .padStart(largo, relleno) / .padEnd(largo, relleno) — rellena hasta cierto largo\n• .repeat(n) — repite el string n veces\n\nTemplate literals (backticks) permiten interpolar variables con ${expresion} y escribir strings multilínea sin concatenar con +.",
        "ejemplo": 'const frase = "  javascript es un lenguaje versátil  ";\n\nconsole.log(frase.trim());                    // "javascript es un lenguaje versátil"\nconsole.log(frase.trim().toUpperCase());      // "JAVASCRIPT ES UN LENGUAJE VERSÁTIL"\nconsole.log(frase.includes("versátil"));      // true\nconsole.log(frase.trim().split(" "));         // ["javascript", "es", "un", "lenguaje", "versátil"]\n\nconst lenguaje = "JavaScript";\nconsole.log(lenguaje.slice(0, 4));   // "Java"\nconsole.log(lenguaje.slice(-6));     // "Script"\nconsole.log(lenguaje.replace("Java", "Type")); // "TypeScript"\n\n// padStart/padEnd — útil para formatear\nconsole.log("7".padStart(3, "0"));   // "007"\nconsole.log("7".padEnd(5, "-"));     // "7----"\n\n// Template literals\nconst nombre = "Ana";\nconst edad = 25;\nconst mensaje = `Hola, soy ${nombre} y tengo ${edad} años.\\nEl año que viene tendré ${edad + 1}.`;\nconsole.log(mensaje);\n\n// Multilínea nativo\nconst poema = `Primera línea\\nSegunda línea\\nTercera línea`;\nconsole.log(poema);',
        "ejercicio": "Dado el string \"   Aprender a Programar es Divertido   \":\n1. Eliminá los espacios extra y mostrá el resultado\n2. Contá cuántas palabras tiene\n3. Convertilo a minúsculas y reemplazá 'programar' por 'codear'\n4. Usando template literals, armá un mensaje que diga cuántos caracteres tiene el string limpio\n5. Formateá el número 5 para que se vea como \"05\" usando padStart",
        "pista": "const limpio = texto.trim(); const palabras = limpio.split(' ').length; — para el mensaje: `El string tiene ${limpio.length} caracteres`"
    },
    {
        "id": 14, "bloque": "Sintaxis moderna", "titulo": "Destructuring de arrays y objetos",
        "descripcion": "Extraé valores de estructuras de forma directa", "xp": 75,
        "teoria": "Destructuring permite extraer valores de arrays u objetos y asignarlos a variables en una sola línea, sin acceder índice por índice o propiedad por propiedad.\n\nArrays (por posición):\nconst [primero, segundo] = [10, 20];\nPodés saltear elementos con comas vacías, o capturar el resto con rest: const [a, ...resto] = [1,2,3,4];\n\nObjetos (por nombre de propiedad):\nconst { nombre, edad } = persona;\nPodés renombrar: const { nombre: nombreCompleto } = persona;\nY dar valores por defecto: const { pais = \"Argentina\" } = persona;\n\nDestructuring anidado: funciona con estructuras dentro de estructuras.\nconst { direccion: { ciudad } } = persona;\n\nEs muy usado en parámetros de función, para recibir un objeto de opciones de forma clara.",
        "ejemplo": 'const coordenadas = [10, 20, 30];\nconst [x, y, z] = coordenadas;\nconsole.log(x, y, z); // 10 20 30\n\n// Saltear elementos\nconst [primero, , tercero] = coordenadas;\nconsole.log(primero, tercero); // 10 30\n\n// Rest en arrays\nconst [cabeza, ...cola] = [1, 2, 3, 4, 5];\nconsole.log(cabeza); // 1\nconsole.log(cola);   // [2, 3, 4, 5]\n\n// Intercambiar variables sin variable auxiliar\nlet a = 1, b = 2;\n[a, b] = [b, a];\nconsole.log(a, b); // 2 1\n\n// Objetos\nconst persona = {\n    nombre: "Valentina",\n    edad: 28,\n    direccion: { ciudad: "Rosario", pais: "Argentina" },\n};\n\nconst { nombre, edad } = persona;\nconsole.log(nombre, edad); // Valentina 28\n\n// Renombrar y valor por defecto\nconst { nombre: nombreCompleto, profesion = "Sin especificar" } = persona;\nconsole.log(nombreCompleto, profesion); // Valentina Sin especificar\n\n// Anidado\nconst { direccion: { ciudad } } = persona;\nconsole.log(ciudad); // Rosario\n\n// En parámetros de función\nfunction mostrarPerfil({ nombre, edad, direccion: { ciudad } }) {\n    console.log(`${nombre} (${edad}) vive en ${ciudad}`);\n}\nmostrarPerfil(persona);',
        "ejercicio": "1. Dado un array [nombre, apellido, edad], extraé cada valor con destructuring\n2. Dado un objeto libro con titulo, autor y un objeto anidado publicacion { anio, editorial }, extraé titulo y anio con destructuring anidado\n3. Escribí una función mostrarProducto que reciba un objeto {nombre, precio} usando destructuring en los parámetros\n4. Intercambiá los valores de dos variables usando destructuring de arrays, sin una variable auxiliar",
        "pista": "function mostrarProducto({ nombre, precio }) { console.log(`${nombre}: $${precio}`); } — para el anidado: const { publicacion: { anio } } = libro;"
    },
    {
        "id": 15, "bloque": "Objetos y estructuras de datos", "titulo": "Objetos: propiedades y métodos",
        "descripcion": "Modelá datos del mundo real con objetos", "xp": 75,
        "teoria": "Los objetos en JS son colecciones de pares clave-valor. Pueden contener valores de cualquier tipo, incluyendo funciones (métodos).\n\nCrear y acceder:\nconst obj = { clave: valor };\nobj.clave o obj[\"clave\"] (útil cuando la clave es dinámica)\n\nMétodos: funciones dentro de un objeto. Dentro de un método, this se refiere al objeto que lo contiene (¡ojo con las arrow functions, que NO tienen su propio this!).\n\nUtilidades del objeto Object:\n• Object.keys(obj) — array de claves\n• Object.values(obj) — array de valores\n• Object.entries(obj) — array de pares [clave, valor]\n• Object.assign({}, obj) — copia superficial\n• Object.freeze(obj) — vuelve el objeto inmutable\n\nPropiedades computadas: podés usar una expresión entre [] como nombre de clave al crear el objeto.",
        "ejemplo": 'const producto = {\n    nombre: "Teclado mecánico",\n    precio: 15000,\n    stock: 8,\n    aplicarDescuento(porcentaje) {\n        this.precio = this.precio - (this.precio * porcentaje / 100);\n        return this.precio;\n    },\n    resumen() {\n        return `${this.nombre}: $${this.precio} (${this.stock} unidades)`;\n    },\n};\n\nconsole.log(producto.resumen());\nproducto.aplicarDescuento(10);\nconsole.log(producto.resumen());\n\n// Acceso dinámico\nconst clave = "stock";\nconsole.log(producto[clave]); // 8\n\n// Object.keys / values / entries\nconsole.log(Object.keys(producto));\nfor (const [clave, valor] of Object.entries({ a: 1, b: 2, c: 3 })) {\n    console.log(`${clave} = ${valor}`);\n}\n\n// Propiedad computada\nconst campo = "email";\nconst usuario = {\n    nombre: "Tomás",\n    [campo]: "tomas@mail.com", // clave dinámica\n};\nconsole.log(usuario);\n\n// Object.freeze\nconst config = Object.freeze({ version: "1.0" });\nconfig.version = "2.0"; // no hace nada, sin error en modo no estricto\nconsole.log(config.version); // "1.0"',
        "ejercicio": "1. Creá un objeto cuentaBancaria con saldo, titular y métodos depositar(monto) y retirar(monto)\n2. Agregá un método resumen() que devuelva un string describiendo la cuenta\n3. Usá Object.entries() para recorrer e imprimir todas las propiedades de un objeto configuracion\n4. Creá un objeto con una propiedad de nombre dinámico usando una variable como clave computada",
        "pista": "depositar(monto) { this.saldo += monto; } — recordá usar function normal o método abreviado {}, no arrow function, para que 'this' funcione."
    },
    {
        "id": 16, "bloque": "Objetos y estructuras de datos", "titulo": "Map y Set",
        "descripcion": "Estructuras de datos especializadas de JS", "xp": 100,
        "teoria": "Además de objetos y arrays, JS tiene dos estructuras especializadas:\n\nMap: colección de pares clave-valor, como un objeto, pero:\n• Las claves pueden ser de CUALQUIER tipo (no solo strings)\n• Mantiene el orden de inserción\n• Tiene .size (no .length)\n• Métodos: .set(clave, valor), .get(clave), .has(clave), .delete(clave)\n\nSet: colección de valores ÚNICOS (sin duplicados).\n• Métodos: .add(valor), .has(valor), .delete(valor)\n• Muy útil para eliminar duplicados de un array: [...new Set(array)]\n\nAmbos son iterables: podés usar for...of directamente sobre ellos.\n\n¿Cuándo usar Map en vez de objeto? Cuando las claves no son strings simples, cuando necesitás el orden garantizado, o cuando agregás/quitás claves con frecuencia.",
        "ejemplo": 'const inventario = new Map();\ninventario.set("manzanas", 50);\ninventario.set("bananas", 30);\ninventario.set("peras", 20);\n\nconsole.log(inventario.get("bananas")); // 30\nconsole.log(inventario.has("uvas"));    // false\nconsole.log(inventario.size);           // 3\n\ninventario.set("bananas", 25); // actualiza\ninventario.delete("peras");\n\nfor (const [fruta, cantidad] of inventario) {\n    console.log(`${fruta}: ${cantidad}`);\n}\n\n// Set: valores únicos\nconst numerosConDuplicados = [1, 2, 2, 3, 4, 4, 4, 5];\nconst unicos = new Set(numerosConDuplicados);\nconsole.log(unicos);              // Set(5) {1, 2, 3, 4, 5}\nconsole.log([...unicos]);         // [1, 2, 3, 4, 5]\nconsole.log(unicos.size);         // 5\n\nconst tags = new Set();\ntags.add("javascript");\ntags.add("web");\ntags.add("javascript"); // se ignora, ya existe\nconsole.log(tags.has("web"));     // true\nconsole.log(tags);                // Set(2) {"javascript", "web"}\n\n// Combinar dos sets (unión)\nconst setA = new Set([1, 2, 3]);\nconst setB = new Set([3, 4, 5]);\nconst union = new Set([...setA, ...setB]);\nconsole.log([...union]); // [1, 2, 3, 4, 5]',
        "ejercicio": "1. Creá un Map llamado precios con al menos 4 productos y sus precios\n2. Actualizá el precio de uno y eliminá otro\n3. Recorré el Map con for...of mostrando cada producto\n4. Dado un array con emails repetidos, usá Set para obtener solo los emails únicos\n5. Contá cuántos emails únicos había en total",
        "pista": "const unicos = [...new Set(arrayConDuplicados)]; console.log('Total únicos:', unicos.length);"
    },
    {
        "id": 17, "bloque": "Objetos y estructuras de datos", "titulo": "JSON: stringify y parse",
        "descripcion": "El formato universal para intercambiar datos", "xp": 100,
        "teoria": "JSON (JavaScript Object Notation) es el formato estándar para intercambiar datos entre sistemas — lo vas a ver constantemente en APIs, archivos de configuración y almacenamiento.\n\nJS ofrece el objeto global JSON con dos métodos clave:\n\n• JSON.stringify(objeto) — convierte un objeto/array de JS a un string JSON\n• JSON.parse(string) — convierte un string JSON de vuelta a un objeto/array de JS\n\nJSON.stringify acepta un segundo argumento (replacer) y un tercero (espaciado, útil para formatear bonito):\nJSON.stringify(obj, null, 2) — indenta con 2 espacios.\n\nLimitaciones de JSON: no puede representar funciones, undefined, Symbol ni referencias circulares — esas propiedades se omiten al convertir.\n\nJSON.parse lanza una excepción (SyntaxError) si el string no es JSON válido — por eso siempre conviene envolverlo en try/catch cuando el dato viene de una fuente externa.",
        "ejemplo": 'const usuario = {\n    nombre: "Camila",\n    edad: 27,\n    activo: true,\n    hobbies: ["leer", "programar"],\n};\n\n// Objeto -> string JSON\nconst json = JSON.stringify(usuario);\nconsole.log(json);\nconsole.log(typeof json); // "string"\n\n// Formateado con indentación\nconst jsonBonito = JSON.stringify(usuario, null, 2);\nconsole.log(jsonBonito);\n\n// string JSON -> objeto\nconst textoRecibido = \'{"id": 1, "producto": "Mouse", "precio": 5000}\';\nconst datos = JSON.parse(textoRecibido);\nconsole.log(datos.producto, datos.precio); // Mouse 5000\n\n// Copia profunda usando JSON (truco común, con limitaciones)\nconst original = { a: 1, b: { c: 2 } };\nconst copiaProfunda = JSON.parse(JSON.stringify(original));\ncopiaProfunda.b.c = 99;\nconsole.log(original.b.c);      // 2 (no se modificó)\nconsole.log(copiaProfunda.b.c); // 99\n\n// Manejo de errores al parsear\nfunction parsearSeguro(texto) {\n    try {\n        return JSON.parse(texto);\n    } catch (error) {\n        console.log("JSON inválido:", error.message);\n        return null;\n    }\n}\nconsole.log(parsearSeguro(\'{"ok": true}\')); // { ok: true }\nconsole.log(parsearSeguro("no es json"));    // null, con mensaje de error',
        "ejercicio": "1. Creá un objeto tarea con titulo, prioridad y completada, y convertilo a JSON con formato indentado (2 espacios)\n2. Convertí de vuelta ese JSON a objeto con JSON.parse y mostrá el titulo\n3. Escribí una función parsearSeguro(texto) que use try/catch y devuelva null si el JSON es inválido\n4. Probala con un JSON válido y con uno inválido\n5. Usá JSON.parse(JSON.stringify(...)) para hacer una copia profunda de un objeto con una propiedad anidada, y demostrá que modificar la copia no afecta al original",
        "pista": "JSON.stringify(objeto, null, 2) agrega indentación. Para el try/catch: try { return JSON.parse(texto); } catch (e) { return null; }"
    },
    {
        "id": 18, "bloque": "OOP", "titulo": "Clases: constructor y métodos",
        "descripcion": "Programación orientada a objetos en JavaScript", "xp": 125,
        "teoria": "Las clases en JS son 'azúcar sintáctico' sobre el sistema de prototipos — una forma más clara de crear objetos con la misma estructura.\n\nSintaxis básica:\nclass Nombre {\n    constructor(param1, param2) {\n        this.param1 = param1;\n        this.param2 = param2;\n    }\n    metodo() { ... }\n}\n\nEl constructor se ejecuta automáticamente al crear una instancia con new. this dentro de un método se refiere a la instancia actual.\n\nGetters y setters: permiten definir propiedades calculadas que se acceden como si fueran propiedades normales, no funciones.\nget area() { return this.ancho * this.alto; }\n\nMétodos estáticos (static): pertenecen a la clase, no a las instancias — se llaman como Clase.metodo(), útiles para funciones utilitarias relacionadas con la clase.",
        "ejemplo": 'class CuentaBancaria {\n    constructor(titular, saldoInicial = 0) {\n        this.titular = titular;\n        this.saldo = saldoInicial;\n        this.movimientos = [];\n    }\n\n    depositar(monto) {\n        this.saldo += monto;\n        this.movimientos.push(`+${monto}`);\n        return this.saldo;\n    }\n\n    retirar(monto) {\n        if (monto > this.saldo) {\n            console.log("Fondos insuficientes");\n            return this.saldo;\n        }\n        this.saldo -= monto;\n        this.movimientos.push(`-${monto}`);\n        return this.saldo;\n    }\n\n    get resumen() {\n        return `${this.titular} tiene $${this.saldo} (${this.movimientos.length} movimientos)`;\n    }\n\n    static tasaInteres() {\n        return 0.05;\n    }\n}\n\nconst cuenta = new CuentaBancaria("Nicolás", 1000);\ncuenta.depositar(500);\ncuenta.retirar(200);\nconsole.log(cuenta.resumen); // se accede como propiedad, sin ()\nconsole.log(cuenta.movimientos); // ["+500", "-200"]\nconsole.log(CuentaBancaria.tasaInteres()); // 0.05, sin instanciar\n\n// Varias instancias, cada una con su propio estado\nconst cuenta2 = new CuentaBancaria("Sofía", 300);\ncuenta2.depositar(100);\nconsole.log(cuenta.saldo, cuenta2.saldo); // 1300 400 (independientes)',
        "ejercicio": "1. Creá una clase Libro con titulo, autor, paginas y un atributo leido = false\n2. Agregá un método marcarLeido() y un getter estado que devuelva 'Leído' o 'Pendiente'\n3. Creá una clase Biblioteca con un array de libros y métodos agregarLibro(libro) y librosLeidos()\n4. Creá al menos 3 libros, marcá alguno como leído, y mostrá el resumen de la biblioteca",
        "pista": "get estado() { return this.leido ? 'Leído' : 'Pendiente'; } — librosLeidos() { return this.libros.filter(l => l.leido); }"
    },
    {
        "id": 19, "bloque": "OOP", "titulo": "Herencia con extends",
        "descripcion": "Reutilizá y especializá clases", "xp": 125,
        "teoria": "La herencia permite que una clase (hija) reutilice y extienda el comportamiento de otra (padre), evitando duplicar código.\n\nSintaxis:\nclass Hija extends Padre {\n    constructor(...) {\n        super(...); // llama al constructor del padre — OBLIGATORIO antes de usar 'this'\n        this.propiedadNueva = ...;\n    }\n    metodo() {\n        super.metodo(); // llama a la versión del padre, si querés extenderla en vez de reemplazarla\n    }\n}\n\ninstancia instanceof Clase — verifica si un objeto es instancia de una clase (o de sus padres, gracias a la cadena de herencia).\n\nSobreescritura de métodos (override): si la clase hija define un método con el mismo nombre que el padre, la versión de la hija 'gana' cuando se llama sobre una instancia de la hija.\n\nBuena práctica: usá herencia cuando hay una relación real 'es un tipo de'. Si la relación es 'tiene un', preferí composición en vez de herencia.",
        "ejemplo": 'class Empleado {\n    constructor(nombre, salarioBase) {\n        this.nombre = nombre;\n        this.salarioBase = salarioBase;\n    }\n\n    calcularSalario() {\n        return this.salarioBase;\n    }\n\n    describir() {\n        return `${this.nombre} gana $${this.calcularSalario()}`;\n    }\n}\n\nclass Gerente extends Empleado {\n    constructor(nombre, salarioBase, bono) {\n        super(nombre, salarioBase); // inicializa nombre y salarioBase del padre\n        this.bono = bono;\n    }\n\n    // Sobreescribe el método del padre\n    calcularSalario() {\n        return this.salarioBase + this.bono;\n    }\n}\n\nconst empleado = new Empleado("Marcos", 50000);\nconst gerente = new Gerente("Laura", 60000, 15000);\n\nconsole.log(empleado.describir()); // Marcos gana $50000\nconsole.log(gerente.describir());  // Laura gana $75000 (usa el método sobreescrito)\n\nconsole.log(gerente instanceof Gerente);   // true\nconsole.log(gerente instanceof Empleado);  // true (Gerente hereda de Empleado)\nconsole.log(empleado instanceof Gerente);  // false\n\n// Array polimórfico: tratamos distintos tipos de forma uniforme\nconst equipo = [empleado, gerente];\nequipo.forEach(persona => console.log(persona.describir()));',
        "ejercicio": "1. Creá una clase Animal con nombre y un método hacerSonido() que devuelva 'Un sonido genérico'\n2. Creá clases Perro y Gato que extiendan Animal y sobreescriban hacerSonido() con 'Guau' y 'Miau'\n3. Creá un array con instancias de ambas y recorrelo llamando hacerSonido() en cada una\n4. Verificá con instanceof que ambas son instancias de Animal además de su propia clase",
        "pista": "class Perro extends Animal { hacerSonido() { return 'Guau'; } } — recordá llamar super(nombre) en el constructor si agregás propiedades nuevas."
    },
    {
        "id": 20, "bloque": "OOP", "titulo": "Encapsulación con campos privados",
        "descripcion": "Protegé el estado interno de tus clases", "xp": 150,
        "teoria": "La encapsulación es el principio de OOP que dice: el estado interno de un objeto debería estar protegido, y solo accesible/modificable a través de métodos controlados.\n\nJavaScript moderno (ES2022+) soporta campos y métodos privados con el prefijo #:\n\nclass Cuenta {\n    #saldo; // campo privado, solo accesible dentro de la clase\n    constructor(saldoInicial) {\n        this.#saldo = saldoInicial;\n    }\n    #validarMonto(monto) { // método privado\n        return monto > 0;\n    }\n    depositar(monto) {\n        if (this.#validarMonto(monto)) this.#saldo += monto;\n    }\n    get saldo() { return this.#saldo; } // getter público de solo lectura\n}\n\nIntentar acceder a cuenta.#saldo desde afuera de la clase da un error de sintaxis — es una protección real del lenguaje, no una convención (a diferencia del guion bajo _saldo que usan otros lenguajes, que es solo una señal visual sin protección real).\n\n¿Por qué encapsular? Evita que código externo deje el objeto en un estado inválido y te da control total sobre cómo se puede modificar el estado.",
        "ejemplo": 'class CajaFuerte {\n    #clave;\n    #contenido;\n    #intentos = 0;\n\n    constructor(clave) {\n        this.#clave = clave;\n        this.#contenido = [];\n    }\n\n    #clavesCoinciden(intento) {\n        return intento === this.#clave;\n    }\n\n    guardar(clave, objeto) {\n        if (!this.#clavesCoinciden(clave)) {\n            this.#intentos++;\n            return "Clave incorrecta";\n        }\n        this.#contenido.push(objeto);\n        return "Guardado";\n    }\n\n    abrir(clave) {\n        if (!this.#clavesCoinciden(clave)) {\n            this.#intentos++;\n            return null;\n        }\n        return [...this.#contenido]; // devuelve una copia, no la referencia interna\n    }\n\n    get intentosFallidos() {\n        return this.#intentos;\n    }\n}\n\nconst caja = new CajaFuerte("1234");\nconsole.log(caja.guardar("0000", "documento")); // Clave incorrecta\nconsole.log(caja.guardar("1234", "documento")); // Guardado\nconsole.log(caja.abrir("1234"));                 // ["documento"]\nconsole.log(caja.intentosFallidos);              // 1\n\n// console.log(caja.#contenido); // SyntaxError: campo privado, no se puede acceder desde afuera',
        "ejercicio": "1. Creá una clase Termostato con un campo privado #temperatura (inicial 20)\n2. Agregá métodos subir(grados) y bajar(grados) que no permitan que la temperatura salga del rango 10-30\n3. Agregá un getter publico temperatura que devuelva el valor actual\n4. Agregá un método privado #dentroDeRango(valor) usado internamente por subir/bajar para validar\n5. Probá que intentar bajar demasiado o subir demasiado no rompe el límite",
        "pista": "#dentroDeRango(valor) { return valor >= 10 && valor <= 30; } — subir(grados) { const nuevo = this.#temperatura + grados; if (this.#dentroDeRango(nuevo)) this.#temperatura = nuevo; }"
    },
    {
        "id": 21, "bloque": "Manejo de errores", "titulo": "try / catch / finally",
        "descripcion": "Manejá errores sin que tu programa se rompa", "xp": 100,
        "teoria": "Cuando algo falla en tiempo de ejecución, JavaScript lanza (throw) un error. Si no lo manejás, el programa se detiene.\n\ntry/catch/finally:\ntry {\n    // código que puede fallar\n} catch (error) {\n    // se ejecuta SOLO si algo en el try lanzó un error\n} finally {\n    // se ejecuta SIEMPRE, haya error o no (útil para limpiar recursos)\n}\n\nEl objeto error (instancia de Error) tiene propiedades útiles:\n• error.message — descripción del error\n• error.name — tipo de error (TypeError, RangeError, SyntaxError, etc.)\n\nthrow: para lanzar tus propios errores cuando detectás una condición inválida.\nthrow new Error(\"mensaje descriptivo\");\n\nEn código async, try/catch envuelve el await para capturar tanto errores síncronos como rechazos de promesas.",
        "ejemplo": 'function dividir(a, b) {\n    if (typeof a !== "number" || typeof b !== "number") {\n        throw new TypeError("Ambos argumentos deben ser números");\n    }\n    if (b === 0) {\n        throw new Error("No se puede dividir por cero");\n    }\n    return a / b;\n}\n\nfunction dividirSeguro(a, b) {\n    try {\n        const resultado = dividir(a, b);\n        console.log(`Resultado: ${resultado}`);\n        return resultado;\n    } catch (error) {\n        console.log(`Error (${error.name}): ${error.message}`);\n        return null;\n    } finally {\n        console.log("Operación de división finalizada");\n    }\n}\n\ndividirSeguro(10, 2);   // Resultado: 5 / Operación finalizada\ndividirSeguro(10, 0);   // Error (Error): No se puede dividir por cero / finalizada\ndividirSeguro(10, "a"); // Error (TypeError): ... / finalizada\n\n// Parseo seguro de JSON\nfunction parsearConfiguracion(texto) {\n    try {\n        return JSON.parse(texto);\n    } catch (error) {\n        console.log("Configuración inválida, usando valores por defecto");\n        return { tema: "claro", idioma: "es" };\n    }\n}\nconsole.log(parsearConfiguracion(\'{"tema": "oscuro"}\'));\nconsole.log(parsearConfiguracion("texto roto"));',
        "ejercicio": "1. Escribí una función validarEdad(edad) que lance un Error si edad es negativa o mayor a 120\n2. Escribí una función registrarUsuario(nombre, edad) que use try/catch para llamar a validarEdad y devuelva un mensaje de éxito o de error\n3. Agregá un bloque finally que imprima 'Intento de registro procesado' siempre\n4. Probala con al menos 2 edades inválidas y 1 válida",
        "pista": "if (edad < 0 || edad > 120) throw new Error('Edad fuera de rango'); — try { validarEdad(edad); return 'Registrado'; } catch (e) { return e.message; } finally { console.log('...'); }"
    },
    {
        "id": 22, "bloque": "Manejo de errores", "titulo": "Errores personalizados",
        "descripcion": "Creá tus propios tipos de error", "xp": 125,
        "teoria": "Podés crear tus propias clases de error extendiendo la clase built-in Error. Esto te permite distinguir entre distintos tipos de fallas en un catch, en vez de tener que parsear el mensaje de texto.\n\nclass ErrorDeValidacion extends Error {\n    constructor(mensaje, campo) {\n        super(mensaje); // inicializa message en la clase padre\n        this.name = \"ErrorDeValidacion\"; // sobreescribe el name por defecto ('Error')\n        this.campo = campo; // podés agregar propiedades propias\n    }\n}\n\nEn el catch, podés usar instanceof para reaccionar distinto según el tipo de error:\ncatch (error) {\n    if (error instanceof ErrorDeValidacion) { ... }\n    else { ... } // error inesperado\n}\n\nEsto es especialmente útil en aplicaciones grandes donde distintos módulos lanzan distintos tipos de error y cada uno necesita un manejo diferente.",
        "ejemplo": 'class ErrorDeValidacion extends Error {\n    constructor(mensaje, campo) {\n        super(mensaje);\n        this.name = "ErrorDeValidacion";\n        this.campo = campo;\n    }\n}\n\nclass ErrorDeStock extends Error {\n    constructor(mensaje, disponible) {\n        super(mensaje);\n        this.name = "ErrorDeStock";\n        this.disponible = disponible;\n    }\n}\n\nfunction validarPedido(producto, cantidad, stockDisponible) {\n    if (!producto || producto.trim() === "") {\n        throw new ErrorDeValidacion("El producto es obligatorio", "producto");\n    }\n    if (cantidad <= 0) {\n        throw new ErrorDeValidacion("La cantidad debe ser mayor a 0", "cantidad");\n    }\n    if (cantidad > stockDisponible) {\n        throw new ErrorDeStock(`Solo hay ${stockDisponible} unidades`, stockDisponible);\n    }\n    return `Pedido de ${cantidad} ${producto} confirmado`;\n}\n\nfunction procesarPedido(producto, cantidad, stock) {\n    try {\n        console.log(validarPedido(producto, cantidad, stock));\n    } catch (error) {\n        if (error instanceof ErrorDeValidacion) {\n            console.log(`Dato inválido en \'${error.campo}\': ${error.message}`);\n        } else if (error instanceof ErrorDeStock) {\n            console.log(`Sin stock suficiente (disponible: ${error.disponible}): ${error.message}`);\n        } else {\n            console.log("Error inesperado:", error.message);\n        }\n    }\n}\n\nprocesarPedido("Mouse", 2, 5);   // confirmado\nprocesarPedido("", 2, 5);        // error de validación (producto)\nprocesarPedido("Mouse", 10, 5);  // error de stock',
        "ejercicio": "1. Creá una clase ErrorDeAutenticacion que extienda Error, con una propiedad extra codigo\n2. Escribí una función login(usuario, clave) que lance ErrorDeAutenticacion si usuario o clave están vacíos, con un codigo distinto para cada caso\n3. En un try/catch, usá instanceof para capturar ese error específico y mostrar un mensaje distinto al de un error genérico\n4. Probá con credenciales vacías y con credenciales válidas",
        "pista": "class ErrorDeAutenticacion extends Error { constructor(mensaje, codigo) { super(mensaje); this.name = 'ErrorDeAutenticacion'; this.codigo = codigo; } }"
    },
    {
        "id": 23, "bloque": "Casos reales", "titulo": "Sistema de inventario",
        "descripcion": "Combiná objetos, arrays y funciones en un caso real", "xp": 175,
        "teoria": "Esta misión no enseña un concepto nuevo: integra todo lo que aprendiste (objetos, clases, arrays funcionales, destructuring, manejo de errores) en un programa más grande, como los que vas a escribir en la vida real.\n\nUn sistema de inventario típico necesita:\n• Una estructura para representar productos (objeto o clase)\n• Operaciones: agregar, quitar stock, buscar, listar con filtros\n• Cálculos derivados: valor total, productos con bajo stock\n• Manejo de casos inválidos (producto inexistente, cantidad negativa)\n\nPensar en 'capas' ayuda a organizar el código: una capa de datos (el array de productos), una capa de operaciones (funciones que lo modifican) y una capa de reportes (funciones que solo leen y calculan, sin modificar nada).",
        "ejemplo": 'class Inventario {\n    constructor() {\n        this.productos = [];\n    }\n\n    agregarProducto(nombre, precio, stock) {\n        if (this.productos.some(p => p.nombre === nombre)) {\n            throw new Error(`${nombre} ya existe en el inventario`);\n        }\n        this.productos.push({ nombre, precio, stock });\n    }\n\n    venderProducto(nombre, cantidad) {\n        const producto = this.productos.find(p => p.nombre === nombre);\n        if (!producto) throw new Error(`${nombre} no encontrado`);\n        if (producto.stock < cantidad) throw new Error(`Stock insuficiente de ${nombre}`);\n        producto.stock -= cantidad;\n        return producto.stock;\n    }\n\n    valorTotal() {\n        return this.productos.reduce((total, p) => total + p.precio * p.stock, 0);\n    }\n\n    bajoStock(minimo = 5) {\n        return this.productos.filter(p => p.stock < minimo).map(p => p.nombre);\n    }\n\n    reporte() {\n        console.log("--- Inventario ---");\n        this.productos.forEach(({ nombre, precio, stock }) => {\n            console.log(`${nombre}: $${precio} x ${stock} = $${precio * stock}`);\n        });\n        console.log(`Valor total: $${this.valorTotal()}`);\n        console.log(`Bajo stock: ${this.bajoStock().join(", ") || "ninguno"}`);\n    }\n}\n\nconst tienda = new Inventario();\ntienda.agregarProducto("Teclado", 15000, 10);\ntienda.agregarProducto("Mouse", 5000, 3);\ntienda.agregarProducto("Monitor", 80000, 4);\n\ntienda.venderProducto("Teclado", 4);\ntienda.reporte();\n\ntry {\n    tienda.venderProducto("Webcam", 1);\n} catch (error) {\n    console.log("Error al vender:", error.message);\n}',
        "ejercicio": "Construí tu propio sistema de inventario (podés basarte en el ejemplo o hacer el tuyo desde cero):\n1. Una clase o conjunto de funciones para agregar productos (nombre, precio, stock)\n2. Un método/función para vender (restar stock) que lance error si no hay suficiente\n3. Un método/función para reponer stock (sumar)\n4. Un reporte que muestre el valor total del inventario y los productos con stock bajo (menos de 5)\n5. Probá al menos un caso de error usando try/catch",
        "pista": "Organizá primero los datos (array de objetos o clase), después las operaciones que los modifican, y al final las funciones de reporte que solo leen — no mezcles las tres cosas en una sola función gigante."
    },
    {
        "id": 24, "bloque": "Casos reales", "titulo": "Procesador de calificaciones",
        "descripcion": "Análisis de datos con métodos funcionales de arrays", "xp": 175,
        "teoria": "Procesar listas de datos es una de las tareas más comunes en programación real, y JS con sus métodos funcionales (map, filter, reduce, sort) es especialmente bueno para esto.\n\nUn flujo típico de análisis de datos:\n1. Partir de una lista 'cruda' de registros (array de objetos)\n2. Filtrar según algún criterio\n3. Transformar/calcular valores derivados\n4. Agregar (reducir) a estadísticas: promedio, máximo, mínimo, conteos\n5. Ordenar para presentar un ranking\n\nAgrupar datos por categoría es un patrón muy común: se hace con reduce, construyendo un objeto donde cada clave es la categoría.",
        "ejemplo": 'const calificaciones = [\n    { estudiante: "Ana", materia: "Matemática", nota: 85 },\n    { estudiante: "Luis", materia: "Matemática", nota: 42 },\n    { estudiante: "Ana", materia: "Historia", nota: 90 },\n    { estudiante: "Marta", materia: "Matemática", nota: 78 },\n    { estudiante: "Luis", materia: "Historia", nota: 65 },\n];\n\n// Promedio general\nconst promedio = calificaciones.reduce((acc, c) => acc + c.nota, 0) / calificaciones.length;\nconsole.log("Promedio general:", promedio.toFixed(1));\n\n// Aprobados (>= 60)\nconst aprobados = calificaciones.filter(c => c.nota >= 60);\nconsole.log("Aprobados:", aprobados.length, "de", calificaciones.length);\n\n// Agrupar por materia\nconst porMateria = calificaciones.reduce((grupos, c) => {\n    if (!grupos[c.materia]) grupos[c.materia] = [];\n    grupos[c.materia].push(c.nota);\n    return grupos;\n}, {});\nconsole.log(porMateria);\n\n// Promedio por materia\nfor (const [materia, notas] of Object.entries(porMateria)) {\n    const prom = notas.reduce((a, b) => a + b, 0) / notas.length;\n    console.log(`${materia}: promedio ${prom.toFixed(1)}`);\n}\n\n// Ranking: mejor nota por estudiante, ordenado descendente\nconst mejorPorEstudiante = Object.values(\n    calificaciones.reduce((acc, c) => {\n        if (!acc[c.estudiante] || c.nota > acc[c.estudiante].nota) acc[c.estudiante] = c;\n        return acc;\n    }, {})\n).sort((a, b) => b.nota - a.nota);\n\nmejorPorEstudiante.forEach((c, i) => console.log(`${i + 1}. ${c.estudiante} — ${c.nota} (${c.materia})`));',
        "ejercicio": "Con un array de al menos 8 registros {estudiante, materia, nota}:\n1. Calculá el promedio general\n2. Filtrá y contá cuántos reprobaron (nota < 60)\n3. Agrupá las notas por materia usando reduce\n4. Calculá el promedio de cada materia\n5. Armá un ranking de los 3 estudiantes con mejor nota (una sola por estudiante, la más alta), ordenado de mayor a menor",
        "pista": "Para agrupar: array.reduce((grupos, item) => { (grupos[item.clave] ??= []).push(item); return grupos; }, {}) — para el ranking: .sort((a, b) => b.nota - a.nota).slice(0, 3)"
    },
    {
        "id": 25, "bloque": "Casos reales", "titulo": "Agenda de contactos en memoria",
        "descripcion": "CRUD completo: crear, leer, actualizar y borrar", "xp": 200,
        "teoria": "CRUD (Create, Read, Update, Delete) es el patrón detrás de casi cualquier aplicación que gestiona datos. Esta misión final te hace construir un CRUD completo en memoria, el mismo patrón que después vas a implementar contra una base de datos real.\n\nDiseño recomendado:\n• Create: agregar un nuevo registro con un id único (contador incremental, o Date.now())\n• Read: buscar uno por id, o listar todos (con filtros opcionales)\n• Update: encontrar por id y modificar sus propiedades (spread o Object.assign para no perder las que no cambian)\n• Delete: quitar del array por id (filter es ideal: devuelve todo MENOS el que coincide)\n\nValidar antes de operar es clave: actualizar o borrar un id que no existe debería informarlo claramente, no fallar en silencio ni romper el programa.",
        "ejemplo": 'class Agenda {\n    constructor() {\n        this.contactos = [];\n        this.siguienteId = 1;\n    }\n\n    crear({ nombre, telefono, email }) {\n        const contacto = { id: this.siguienteId++, nombre, telefono, email };\n        this.contactos.push(contacto);\n        return contacto;\n    }\n\n    buscarPorId(id) {\n        return this.contactos.find(c => c.id === id) ?? null;\n    }\n\n    buscarPorNombre(texto) {\n        return this.contactos.filter(c =>\n            c.nombre.toLowerCase().includes(texto.toLowerCase())\n        );\n    }\n\n    actualizar(id, cambios) {\n        const contacto = this.buscarPorId(id);\n        if (!contacto) throw new Error(`No existe contacto con id ${id}`);\n        Object.assign(contacto, cambios);\n        return contacto;\n    }\n\n    eliminar(id) {\n        const existia = this.buscarPorId(id) !== null;\n        this.contactos = this.contactos.filter(c => c.id !== id);\n        return existia;\n    }\n\n    listar() {\n        return [...this.contactos]; // copia, no la referencia interna\n    }\n}\n\nconst agenda = new Agenda();\nagenda.crear({ nombre: "Julia Fernández", telefono: "111-222", email: "julia@mail.com" });\nagenda.crear({ nombre: "Pedro Gómez", telefono: "333-444", email: "pedro@mail.com" });\n\nconsole.log(agenda.listar());\nagenda.actualizar(1, { telefono: "999-888" });\nconsole.log(agenda.buscarPorId(1));\n\nconsole.log(agenda.buscarPorNombre("gómez"));\n\ntry {\n    agenda.actualizar(99, { nombre: "Nadie" });\n} catch (error) {\n    console.log("Error:", error.message);\n}\n\nconsole.log("Eliminado:", agenda.eliminar(2));\nconsole.log(agenda.listar());',
        "ejercicio": "Implementá tu propia Agenda (clase o funciones, a elección):\n1. crear(datos) — agrega un contacto con id autoincremental\n2. buscarPorId(id) y buscarPorNombre(texto) (búsqueda parcial, sin distinguir mayúsculas)\n3. actualizar(id, cambios) — lanza error si el id no existe\n4. eliminar(id) — devuelve true/false según si existía\n5. Probá el flujo completo: creá 4 contactos, actualizá uno, buscá por nombre parcial, eliminá uno, y mostrá el listado final",
        "pista": "Para actualizar sin perder propiedades: Object.assign(contacto, cambios) o { ...contacto, ...cambios }. Para eliminar: this.contactos = this.contactos.filter(c => c.id !== id);"
    }
]


@router.get("/modulos/javascript")
def get_modulos_javascript():
    return MODULOS_JS
